// Places data - extracted from app.js
// Total: 58 places
const PLACES_DATA = [
  {
    "id": "kato-pafos-archaeological-park",
    "nameKey": "places.kato-pafos-archaeological-park.name",
    "descriptionKey": "places.kato-pafos-archaeological-park.description",
    "badgeKey": "places.kato-pafos-archaeological-park.badge",
    "lat": 34.75567,
    "lng": 32.40417,
    "googleMapsUrl": "https://maps.google.com/?q=34.75567,32.40417",
    "xp": 210,
    "requiredLevel": 6
  },
  {
    "id": "tombs-of-the-kings",
    "nameKey": "places.tombs-of-the-kings.name",
    "descriptionKey": "places.tombs-of-the-kings.description",
    "badgeKey": "places.tombs-of-the-kings.badge",
    "lat": 34.775,
    "lng": 32.40694,
    "googleMapsUrl": "https://maps.google.com/?q=34.77500,32.40694",
    "xp": 190,
    "requiredLevel": 5
  },
  {
    "id": "coral-bay",
    "nameKey": "places.coral-bay.name",
    "descriptionKey": "places.coral-bay.description",
    "badgeKey": "places.coral-bay.badge",
    "lat": 34.854,
    "lng": 32.3695,
    "googleMapsUrl": "https://maps.google.com/?q=34.85400,32.36950",
    "xp": 110,
    "requiredLevel": 1
  },
  {
    "id": "aphrodite-rock",
    "nameKey": "places.aphrodite-rock.name",
    "descriptionKey": "places.aphrodite-rock.description",
    "badgeKey": "places.aphrodite-rock.badge",
    "lat": 34.6641,
    "lng": 32.6271,
    "googleMapsUrl": "https://maps.google.com/?q=34.66410,32.62710",
    "xp": 120,
    "requiredLevel": 1
  },
  {
    "id": "blue-lagoon-akamas",
    "nameKey": "places.blue-lagoon-akamas.name",
    "descriptionKey": "places.blue-lagoon-akamas.description",
    "badgeKey": "places.blue-lagoon-akamas.badge",
    "lat": 35.08417,
    "lng": 32.30611,
    "googleMapsUrl": "https://maps.google.com/?q=35.08417,32.30611",
    "xp": 220,
    "requiredLevel": 7
  },
  {
    "id": "kourion-archaeological-site",
    "nameKey": "places.kourion-archaeological-site.name",
    "descriptionKey": "places.kourion-archaeological-site.description",
    "badgeKey": "places.kourion-archaeological-site.badge",
    "lat": 34.6642,
    "lng": 32.8877,
    "googleMapsUrl": "https://maps.google.com/?q=34.66420,32.88770",
    "xp": 200,
    "requiredLevel": 6
  },
  {
    "id": "kolossi-castle",
    "nameKey": "places.kolossi-castle.name",
    "descriptionKey": "places.kolossi-castle.description",
    "badgeKey": "places.kolossi-castle.badge",
    "lat": 34.66527,
    "lng": 32.93396,
    "googleMapsUrl": "https://maps.google.com/?q=34.66527,32.93396",
    "xp": 170,
    "requiredLevel": 4
  },
  {
    "id": "molos-promenade",
    "nameKey": "places.molos-promenade.name",
    "descriptionKey": "places.molos-promenade.description",
    "badgeKey": "places.molos-promenade.badge",
    "lat": 34.67658,
    "lng": 33.04979,
    "googleMapsUrl": "https://maps.google.com/?q=34.67658,33.04979",
    "xp": 130,
    "requiredLevel": 2
  },
  {
    "id": "amathus-ruins",
    "nameKey": "places.amathus-ruins.name",
    "descriptionKey": "places.amathus-ruins.description",
    "badgeKey": "places.amathus-ruins.badge",
    "lat": 34.7125,
    "lng": 33.14167,
    "googleMapsUrl": "https://maps.google.com/?q=34.71250,33.14167",
    "xp": 180,
    "requiredLevel": 5
  },
  {
    "id": "limassol-castle",
    "nameKey": "places.limassol-castle.name",
    "descriptionKey": "places.limassol-castle.description",
    "badgeKey": "places.limassol-castle.badge",
    "lat": 34.6722,
    "lng": 33.0415,
    "googleMapsUrl": "https://maps.google.com/?q=34.67220,33.04150",
    "xp": 160,
    "requiredLevel": 3
  },
  {
    "id": "saint-lazarus-church",
    "nameKey": "places.saint-lazarus-church.name",
    "descriptionKey": "places.saint-lazarus-church.description",
    "badgeKey": "places.saint-lazarus-church.badge",
    "lat": 34.9125,
    "lng": 33.6333,
    "googleMapsUrl": "https://maps.google.com/?q=34.91250,33.63330",
    "xp": 150,
    "requiredLevel": 3
  },
  {
    "id": "larnaca-salt-lake-hala-sultan",
    "nameKey": "places.larnaca-salt-lake-hala-sultan.name",
    "descriptionKey": "places.larnaca-salt-lake-hala-sultan.description",
    "badgeKey": "places.larnaca-salt-lake-hala-sultan.badge",
    "lat": 34.8853,
    "lng": 33.6102,
    "googleMapsUrl": "https://maps.google.com/?q=34.88530,33.61020",
    "xp": 140,
    "requiredLevel": 3
  },
  {
    "id": "finikoudes-beach",
    "nameKey": "places.finikoudes-beach.name",
    "descriptionKey": "places.finikoudes-beach.description",
    "badgeKey": "places.finikoudes-beach.badge",
    "lat": 34.913895,
    "lng": 33.638418,
    "googleMapsUrl": "https://maps.google.com/?q=34.913895,33.638418",
    "xp": 115,
    "requiredLevel": 1
  },
  {
    "id": "chirokitia-archaeological-site",
    "nameKey": "places.chirokitia-archaeological-site.name",
    "descriptionKey": "places.chirokitia-archaeological-site.description",
    "badgeKey": "places.chirokitia-archaeological-site.badge",
    "lat": 34.79672,
    "lng": 33.34372,
    "googleMapsUrl": "https://maps.google.com/?q=34.79672,33.34372",
    "xp": 200,
    "requiredLevel": 5
  },
  {
    "id": "lefkara-village",
    "nameKey": "places.lefkara-village.name",
    "descriptionKey": "places.lefkara-village.description",
    "badgeKey": "places.lefkara-village.badge",
    "lat": 34.867,
    "lng": 33.3,
    "googleMapsUrl": "https://maps.google.com/?q=34.86700,33.30000",
    "xp": 170,
    "requiredLevel": 4
  },
  {
    "id": "nissi-beach",
    "nameKey": "places.nissi-beach.name",
    "descriptionKey": "places.nissi-beach.description",
    "badgeKey": "places.nissi-beach.badge",
    "lat": 34.99,
    "lng": 33.97,
    "googleMapsUrl": "https://maps.google.com/?q=34.99000,33.97000",
    "xp": 120,
    "requiredLevel": 1
  },
  {
    "id": "cape-greco",
    "nameKey": "places.cape-greco.name",
    "descriptionKey": "places.cape-greco.description",
    "badgeKey": "places.cape-greco.badge",
    "lat": 35,
    "lng": 34.01667,
    "googleMapsUrl": "https://maps.google.com/?q=35.00000,34.01667",
    "xp": 210,
    "requiredLevel": 8
  },
  {
    "id": "fig-tree-bay",
    "nameKey": "places.fig-tree-bay.name",
    "descriptionKey": "places.fig-tree-bay.description",
    "badgeKey": "places.fig-tree-bay.badge",
    "lat": 35.012567,
    "lng": 34.058549,
    "googleMapsUrl": "https://maps.google.com/?q=35.012567,34.058549",
    "xp": 125,
    "requiredLevel": 1
  },
  {
    "id": "ayia-napa-monastery",
    "nameKey": "places.ayia-napa-monastery.name",
    "descriptionKey": "places.ayia-napa-monastery.description",
    "badgeKey": "places.ayia-napa-monastery.badge",
    "lat": 34.989202,
    "lng": 33.999746,
    "googleMapsUrl": "https://maps.google.com/?q=34.989202,33.999746",
    "xp": 160,
    "requiredLevel": 3
  },
  {
    "id": "ayia-napa-sculpture-park",
    "nameKey": "places.ayia-napa-sculpture-park.name",
    "descriptionKey": "places.ayia-napa-sculpture-park.description",
    "badgeKey": "places.ayia-napa-sculpture-park.badge",
    "lat": 34.985077,
    "lng": 34.01929,
    "googleMapsUrl": "https://maps.google.com/?q=34.985077,34.019290",
    "xp": 150,
    "requiredLevel": 3
  },
  {
    "id": "troodos-olympos",
    "nameKey": "places.troodos-olympos.name",
    "descriptionKey": "places.troodos-olympos.description",
    "badgeKey": "places.troodos-olympos.badge",
    "lat": 34.93639,
    "lng": 32.86333,
    "googleMapsUrl": "https://maps.google.com/?q=34.93639,32.86333",
    "xp": 200,
    "requiredLevel": 7
  },
  {
    "id": "kykkos-monastery",
    "nameKey": "places.kykkos-monastery.name",
    "descriptionKey": "places.kykkos-monastery.description",
    "badgeKey": "places.kykkos-monastery.badge",
    "lat": 34.98334,
    "lng": 32.741299,
    "googleMapsUrl": "https://maps.google.com/?q=34.98334,32.741299",
    "xp": 190,
    "requiredLevel": 5
  },
  {
    "id": "omodos-village",
    "nameKey": "places.omodos-village.name",
    "descriptionKey": "places.omodos-village.description",
    "badgeKey": "places.omodos-village.badge",
    "lat": 34.84926,
    "lng": 32.80986,
    "googleMapsUrl": "https://maps.google.com/?q=34.84926,32.80986",
    "xp": 170,
    "requiredLevel": 4
  },
  {
    "id": "kakopetria-village",
    "nameKey": "places.kakopetria-village.name",
    "descriptionKey": "places.kakopetria-village.description",
    "badgeKey": "places.kakopetria-village.badge",
    "lat": 34.9876,
    "lng": 32.9015,
    "googleMapsUrl": "https://maps.google.com/?q=34.98760,32.90150",
    "xp": 160,
    "requiredLevel": 3
  },
  {
    "id": "caledonia-waterfall",
    "nameKey": "places.caledonia-waterfall.name",
    "descriptionKey": "places.caledonia-waterfall.description",
    "badgeKey": "places.caledonia-waterfall.badge",
    "lat": 34.90298,
    "lng": 32.86989,
    "googleMapsUrl": "https://maps.google.com/?q=34.90298,32.86989",
    "xp": 180,
    "requiredLevel": 4
  },
  {
    "id": "kyrenia-old-harbour",
    "nameKey": "places.kyrenia-old-harbour.name",
    "descriptionKey": "places.kyrenia-old-harbour.description",
    "badgeKey": "places.kyrenia-old-harbour.badge",
    "lat": 35.34189,
    "lng": 33.320442,
    "googleMapsUrl": "https://maps.google.com/?q=35.34189,33.320442",
    "xp": 150,
    "requiredLevel": 2
  },
  {
    "id": "kyrenia-castle",
    "nameKey": "places.kyrenia-castle.name",
    "descriptionKey": "places.kyrenia-castle.description",
    "badgeKey": "places.kyrenia-castle.badge",
    "lat": 35.34202,
    "lng": 33.32191,
    "googleMapsUrl": "https://maps.google.com/?q=35.34202,33.32191",
    "xp": 180,
    "requiredLevel": 4
  },
  {
    "id": "st-hilarion-castle",
    "nameKey": "places.st-hilarion-castle.name",
    "descriptionKey": "places.st-hilarion-castle.description",
    "badgeKey": "places.st-hilarion-castle.badge",
    "lat": 35.312485,
    "lng": 33.281364,
    "googleMapsUrl": "https://maps.google.com/?q=35.312485,33.281364",
    "xp": 220,
    "requiredLevel": 6
  },
  {
    "id": "famagusta-old-town",
    "nameKey": "places.famagusta-old-town.name",
    "descriptionKey": "places.famagusta-old-town.description",
    "badgeKey": "places.famagusta-old-town.badge",
    "lat": 35.125,
    "lng": 33.94167,
    "googleMapsUrl": "https://maps.google.com/?q=35.12500,33.94167",
    "xp": 210,
    "requiredLevel": 6
  },
  {
    "id": "karpaz-golden-beach",
    "nameKey": "places.karpaz-golden-beach.name",
    "descriptionKey": "places.karpaz-golden-beach.description",
    "badgeKey": "places.karpaz-golden-beach.badge",
    "lat": 35.63889,
    "lng": 34.54389,
    "googleMapsUrl": "https://maps.google.com/?q=35.63889,34.54389",
    "xp": 230,
    "requiredLevel": 7
  },
  {
    "id": "zenobia-wreck",
    "nameKey": "places.zenobia-wreck.name",
    "descriptionKey": "places.zenobia-wreck.description",
    "badgeKey": "places.zenobia-wreck.badge",
    "lat": 34.9,
    "lng": 33.633,
    "googleMapsUrl": "https://maps.google.com/?q=34.90000,33.63300",
    "xp": 240,
    "requiredLevel": 8
  },
  {
    "id": "avakas-gorge",
    "nameKey": "places.avakas-gorge.name",
    "descriptionKey": "places.avakas-gorge.description",
    "badgeKey": "places.avakas-gorge.badge",
    "lat": 34.9935,
    "lng": 32.355,
    "googleMapsUrl": "https://maps.google.com/?q=34.99350,32.35500",
    "xp": 200,
    "requiredLevel": 6
  },
  {
    "id": "aphrodites-baths",
    "nameKey": "places.aphrodites-baths.name",
    "descriptionKey": "places.aphrodites-baths.description",
    "badgeKey": "places.aphrodites-baths.badge",
    "lat": 35.014,
    "lng": 32.367,
    "googleMapsUrl": "https://maps.google.com/?q=35.01400,32.36700",
    "xp": 150,
    "requiredLevel": 3
  },
  {
    "id": "polis-latchi-marina",
    "nameKey": "places.polis-latchi-marina.name",
    "descriptionKey": "places.polis-latchi-marina.description",
    "badgeKey": "places.polis-latchi-marina.badge",
    "lat": 35.038,
    "lng": 32.43,
    "googleMapsUrl": "https://maps.google.com/?q=35.03800,32.43000",
    "xp": 140,
    "requiredLevel": 2
  },
  {
    "id": "st-hilarion-vantage-point",
    "nameKey": "places.st-hilarion-vantage-point.name",
    "descriptionKey": "places.st-hilarion-vantage-point.description",
    "badgeKey": "places.st-hilarion-vantage-point.badge",
    "lat": 35.31,
    "lng": 33.28,
    "googleMapsUrl": "https://maps.google.com/?q=35.31000,33.28000",
    "xp": 160,
    "requiredLevel": 4
  },
  {
    "id": "buffavento-castle",
    "nameKey": "places.buffavento-castle.name",
    "descriptionKey": "places.buffavento-castle.description",
    "badgeKey": "places.buffavento-castle.badge",
    "lat": 35.33,
    "lng": 33.29,
    "googleMapsUrl": "https://maps.google.com/?q=35.33000,33.29000",
    "xp": 210,
    "requiredLevel": 6
  },
  {
    "id": "lania-village",
    "nameKey": "places.lania-village.name",
    "descriptionKey": "places.lania-village.description",
    "badgeKey": "places.lania-village.badge",
    "lat": 34.78,
    "lng": 32.9,
    "googleMapsUrl": "https://maps.google.com/?q=34.78000,32.90000",
    "xp": 120,
    "requiredLevel": 1
  },
  {
    "id": "trooditissa-monastery",
    "nameKey": "places.trooditissa-monastery.name",
    "descriptionKey": "places.trooditissa-monastery.description",
    "badgeKey": "places.trooditissa-monastery.badge",
    "lat": 34.916,
    "lng": 32.819,
    "googleMapsUrl": "https://maps.google.com/?q=34.91600,32.81900",
    "xp": 170,
    "requiredLevel": 4
  },
  {
    "id": "soli-ancient-site",
    "nameKey": "places.soli-ancient-site.name",
    "descriptionKey": "places.soli-ancient-site.description",
    "badgeKey": "places.soli-ancient-site.badge",
    "lat": 35.144,
    "lng": 33.897,
    "googleMapsUrl": "https://maps.google.com/?q=35.14400,33.89700",
    "xp": 180,
    "requiredLevel": 5
  },
  {
    "id": "limassol-municipal-aquarium",
    "nameKey": "places.limassol-municipal-aquarium.name",
    "descriptionKey": "places.limassol-municipal-aquarium.description",
    "badgeKey": "places.limassol-municipal-aquarium.badge",
    "lat": 34.707,
    "lng": 33.069,
    "googleMapsUrl": "https://maps.google.com/?q=34.70700,33.06900",
    "xp": 110,
    "requiredLevel": 1
  },
  {
    "id": "dasoudi-beach",
    "nameKey": "places.dasoudi-beach.name",
    "descriptionKey": "places.dasoudi-beach.description",
    "badgeKey": "places.dasoudi-beach.badge",
    "lat": 34.68,
    "lng": 33.035,
    "googleMapsUrl": "https://maps.google.com/?q=34.68000,33.03500",
    "xp": 115,
    "requiredLevel": 1
  },
  {
    "id": "governors-beach",
    "nameKey": "places.governors-beach.name",
    "descriptionKey": "places.governors-beach.description",
    "badgeKey": "places.governors-beach.badge",
    "lat": 34.725,
    "lng": 33.1,
    "googleMapsUrl": "https://maps.google.com/?q=34.72500,33.10000",
    "xp": 130,
    "requiredLevel": 2
  },
  {
    "id": "macronissos-beach",
    "nameKey": "places.macronissos-beach.name",
    "descriptionKey": "places.macronissos-beach.description",
    "badgeKey": "places.macronissos-beach.badge",
    "lat": 34.9975,
    "lng": 34.02,
    "googleMapsUrl": "https://maps.google.com/?q=34.99750,34.02000",
    "xp": 125,
    "requiredLevel": 1
  },
  {
    "id": "yeroskipou-town",
    "nameKey": "places.yeroskipou-town.name",
    "descriptionKey": "places.yeroskipou-town.description",
    "badgeKey": "places.yeroskipou-town.badge",
    "lat": 34.715,
    "lng": 32.49,
    "googleMapsUrl": "https://maps.google.com/?q=34.71500,32.49000",
    "xp": 135,
    "requiredLevel": 2
  },
  {
    "id": "agios-neophytos-monastery",
    "nameKey": "places.agios-neophytos-monastery.name",
    "descriptionKey": "places.agios-neophytos-monastery.description",
    "badgeKey": "places.agios-neophytos-monastery.badge",
    "lat": 34.822,
    "lng": 32.389,
    "googleMapsUrl": "https://maps.google.com/?q=34.82200,32.38900",
    "xp": 175,
    "requiredLevel": 4
  },
  {
    "id": "vouni-ancient-house",
    "nameKey": "places.vouni-ancient-house.name",
    "descriptionKey": "places.vouni-ancient-house.description",
    "badgeKey": "places.vouni-ancient-house.badge",
    "lat": 34.8,
    "lng": 32.583,
    "googleMapsUrl": "https://maps.google.com/?q=34.80000,32.58300",
    "xp": 190,
    "requiredLevel": 5
  },
  {
    "id": "nicosia-archaeological-museum",
    "nameKey": "places.nicosia-archaeological-museum.name",
    "descriptionKey": "places.nicosia-archaeological-museum.description",
    "badgeKey": "places.nicosia-archaeological-museum.badge",
    "lat": 35.171,
    "lng": 33.365,
    "googleMapsUrl": "https://maps.google.com/?q=35.17100,33.36500",
    "xp": 160,
    "requiredLevel": 3
  },
  {
    "id": "buyuk-han",
    "nameKey": "places.buyuk-han.name",
    "descriptionKey": "places.buyuk-han.description",
    "badgeKey": "places.buyuk-han.badge",
    "lat": 35.176,
    "lng": 33.364,
    "googleMapsUrl": "https://maps.google.com/?q=35.17600,33.36400",
    "xp": 150,
    "requiredLevel": 3
  },
  {
    "id": "ledra-street",
    "nameKey": "places.ledra-street.name",
    "descriptionKey": "places.ledra-street.description",
    "badgeKey": "places.ledra-street.badge",
    "lat": 35.1765,
    "lng": 33.3605,
    "googleMapsUrl": "https://maps.google.com/?q=35.17650,33.36050",
    "xp": 120,
    "requiredLevel": 1
  },
  {
    "id": "eleftheria-square",
    "nameKey": "places.eleftheria-square.name",
    "descriptionKey": "places.eleftheria-square.description",
    "badgeKey": "places.eleftheria-square.badge",
    "lat": 35.173,
    "lng": 33.366,
    "googleMapsUrl": "https://maps.google.com/?q=35.17300,33.36600",
    "xp": 125,
    "requiredLevel": 1
  },
  {
    "id": "anexartisias-street",
    "nameKey": "places.anexartisias-street.name",
    "descriptionKey": "places.anexartisias-street.description",
    "badgeKey": "places.anexartisias-street.badge",
    "lat": 34.7073,
    "lng": 33.0214,
    "googleMapsUrl": "https://maps.google.com/?q=34.70730,33.02140",
    "xp": 115,
    "requiredLevel": 1
  },
  {
    "id": "fasouri-watermania",
    "nameKey": "places.fasouri-watermania.name",
    "descriptionKey": "places.fasouri-watermania.description",
    "badgeKey": "places.fasouri-watermania.badge",
    "lat": 34.682,
    "lng": 33.013,
    "googleMapsUrl": "https://maps.google.com/?q=34.68200,33.01300",
    "xp": 180,
    "requiredLevel": 4
  },
  {
    "id": "akamas-national-park",
    "nameKey": "places.akamas-national-park.name",
    "descriptionKey": "places.akamas-national-park.description",
    "badgeKey": "places.akamas-national-park.badge",
    "lat": 35.041,
    "lng": 32.375,
    "googleMapsUrl": "https://maps.google.com/?q=35.04100,32.37500",
    "xp": 230,
    "requiredLevel": 7
  },
  {
    "id": "panagia-kykkos-viewpoint",
    "nameKey": "places.panagia-kykkos-viewpoint.name",
    "descriptionKey": "places.panagia-kykkos-viewpoint.description",
    "badgeKey": "places.panagia-kykkos-viewpoint.badge",
    "lat": 34.991,
    "lng": 32.741,
    "googleMapsUrl": "https://maps.google.com/?q=34.99100,32.74100",
    "xp": 220,
    "requiredLevel": 7
  },
  {
    "id": "troodos-square",
    "nameKey": "places.troodos-square.name",
    "descriptionKey": "places.troodos-square.description",
    "badgeKey": "places.troodos-square.badge",
    "lat": 34.95,
    "lng": 32.87,
    "googleMapsUrl": "https://maps.google.com/?q=34.95000,32.87000",
    "xp": 140,
    "requiredLevel": 2
  },
  {
    "id": "avakas-gorge-west-entrance",
    "nameKey": "places.avakas-gorge-west-entrance.name",
    "descriptionKey": "places.avakas-gorge-west-entrance.description",
    "badgeKey": "places.avakas-gorge-west-entrance.badge",
    "lat": 35.0005,
    "lng": 32.35,
    "googleMapsUrl": "https://maps.google.com/?q=35.00050,32.35000",
    "xp": 190,
    "requiredLevel": 5
  },
  {
    "id": "cape-greco-sea-caves",
    "nameKey": "places.cape-greco-sea-caves.name",
    "descriptionKey": "places.cape-greco-sea-caves.description",
    "badgeKey": "places.cape-greco-sea-caves.badge",
    "lat": 34.9965,
    "lng": 34.025,
    "googleMapsUrl": "https://maps.google.com/?q=34.99650,34.02500",
    "xp": 200,
    "requiredLevel": 6
  },
  {
    "id": "cyprus-museum",
    "nameKey": "places.cyprus-museum.name",
    "descriptionKey": "places.cyprus-museum.description",
    "badgeKey": "places.cyprus-museum.badge",
    "lat": 35.172,
    "lng": 33.3655,
    "googleMapsUrl": "https://maps.google.com/?q=35.17200,33.36550",
    "xp": 170,
    "requiredLevel": 4
  }
];
