// Tasks data - exported from app.js
const TASKS_DATA = [
  { "id": "sunrise-challenge", "xp": 80, "requiredLevel": 1 },
  { "id": "taste-halloumi", "xp": 95, "requiredLevel": 2 },
  { "id": "nicosia-day-trip", "xp": 130, "requiredLevel": 4 },
  { "id": "troodos-wine-route", "xp": 180, "requiredLevel": 6 },
  { "id": "sea-adventure", "xp": 220, "requiredLevel": 9 },
  { "id": "nicosia-green-line-walk", "xp": 140, "requiredLevel": 3 },
  { "id": "loukoumi-workshop", "xp": 150, "requiredLevel": 4 },
  { "id": "akamas-jeep-safari", "xp": 210, "requiredLevel": 6 },
  { "id": "zenobia-dive-challenge", "xp": 260, "requiredLevel": 8 },
  { "id": "troodos-stargazing", "xp": 180, "requiredLevel": 7 },
  { "id": "limassol-bike-promenade", "xp": 160, "requiredLevel": 3 },
  { "id": "larnaca-art-walk", "xp": 175, "requiredLevel": 5 },
  { "id": "karpaz-donkey-care", "xp": 190, "requiredLevel": 6 },
  { "id": "halloumi-farm-visit", "xp": 200, "requiredLevel": 5 },
  { "id": "sunset-yoga-nissi", "xp": 150, "requiredLevel": 4 },
  { "id": "premium-car-rental", "xp": 210, "requiredLevel": 5 },
  { "id": "private-blue-lagoon-charter", "xp": 240, "requiredLevel": 8 },
  { "id": "troodos-private-tour", "xp": 220, "requiredLevel": 6 },
  { "id": "nicosia-famagusta-combo", "xp": 230, "requiredLevel": 7 },
  { "id": "family-waterpark-day", "xp": 185, "requiredLevel": 4 },
  { "id": "ayia-napa-sunset-cruise", "xp": 215, "requiredLevel": 5 },
  { "id": "wedding-photoshoot-cyprus", "xp": 250, "requiredLevel": 9 }
];
