// Places data - extracted from app.js with fallback values
// Total: 58 places
// NOTE: This is now FALLBACK data. Primary data loads from Supabase via poi-loader.js
const STATIC_PLACES_DATA = [
  {
    "id": "kato-pafos-archaeological-park",
    "nameKey": "places.kato-pafos-archaeological-park.name",
    "nameFallback": "Kato Paphos Archaeological Park (Nea Paphos)",
    "descriptionKey": "places.kato-pafos-archaeological-park.description",
    "descriptionFallback": "Expansive UNESCO site with famous mosaics and the ruins of the ancient city of Nea Paphos.",
    "badgeKey": "places.kato-pafos-archaeological-park.badge",
    "badgeFallback": "Nea Paphos Curator",
    "lat": 34.75567,
    "lng": 32.40417,
    "googleMapsUrl": "https://maps.google.com/?q=34.75567,32.40417",
    "xp": 210,
    "requiredLevel": 6
  },
  {
    "id": "tombs-of-the-kings",
    "nameKey": "places.tombs-of-the-kings.name",
    "nameFallback": "Tombs of the Kings in Paphos",
    "descriptionKey": "places.tombs-of-the-kings.description",
    "descriptionFallback": "Monumental rock-cut tombs from the Hellenistic and Roman periods adorned with Doric columns.",
    "badgeKey": "places.tombs-of-the-kings.badge",
    "badgeFallback": "Necropolis Guardian",
    "lat": 34.775,
    "lng": 32.40694,
    "googleMapsUrl": "https://maps.google.com/?q=34.77500,32.40694",
    "xp": 190,
    "requiredLevel": 5
  },
  {
    "id": "coral-bay",
    "nameKey": "places.coral-bay.name",
    "nameFallback": "Coral Bay Beach",
    "descriptionKey": "places.coral-bay.description",
    "descriptionFallback": "Golden sand, gentle entry into the sea and crystal-clear water—the classic spot to relax near Peyia.",
    "badgeKey": "places.coral-bay.badge",
    "badgeFallback": "Beach Explorer",
    "lat": 34.854,
    "lng": 32.3695,
    "googleMapsUrl": "https://maps.google.com/?q=34.85400,32.36950",
    "xp": 110,
    "requiredLevel": 1
  },
  {
    "id": "aphrodite-rock",
    "nameKey": "places.aphrodite-rock.name",
    "nameFallback": "Skała Afrodyty (Petra tou Romiou)",
    "descriptionKey": "places.aphrodite-rock.description",
    "descriptionFallback": "Legenda głosi, że wśród turkusowych fal u stóp skały narodziła się Afrodyta – idealne miejsce na zachód słońca.",
    "badgeKey": "places.aphrodite-rock.badge",
    "badgeFallback": "Strażnik Mitów",
    "lat": 34.6641,
    "lng": 32.6271,
    "googleMapsUrl": "https://maps.google.com/?q=34.66410,32.62710",
    "xp": 120,
    "requiredLevel": 1
  },
  {
    "id": "blue-lagoon-akamas",
    "nameKey": "places.blue-lagoon-akamas.name",
    "nameFallback": "Błękitna Laguna (Akamas)",
    "descriptionKey": "places.blue-lagoon-akamas.description",
    "descriptionFallback": "Krystalicznie czysta zatoka otoczona dziką przyrodą półwyspu Akamas – raj do snorkelingu.",
    "badgeKey": "places.blue-lagoon-akamas.badge",
    "badgeFallback": "Łowca Turkusu",
    "lat": 35.08417,
    "lng": 32.30611,
    "googleMapsUrl": "https://maps.google.com/?q=35.08417,32.30611",
    "xp": 220,
    "requiredLevel": 7
  },
  {
    "id": "kourion-archaeological-site",
    "nameKey": "places.kourion-archaeological-site.name",
    "nameFallback": "Stanowisko archeologiczne Kurion",
    "descriptionKey": "places.kourion-archaeological-site.description",
    "descriptionFallback": "Ruiny antycznego miasta na klifie z teatrem, łaźniami i mozaikami Domu Eustoliosa.",
    "badgeKey": "places.kourion-archaeological-site.badge",
    "badgeFallback": "Obrońca Kurionu",
    "lat": 34.6642,
    "lng": 32.8877,
    "googleMapsUrl": "https://maps.google.com/?q=34.66420,32.88770",
    "xp": 200,
    "requiredLevel": 6
  },
  {
    "id": "kolossi-castle",
    "nameKey": "places.kolossi-castle.name",
    "nameFallback": "Zamek Kolossi",
    "descriptionKey": "places.kolossi-castle.description",
    "descriptionFallback": "XIII-wieczna forteca joannitów, dawne centrum produkcji słodkiego wina Commandaria.",
    "badgeKey": "places.kolossi-castle.badge",
    "badgeFallback": "Rycerz Kolossi",
    "lat": 34.66527,
    "lng": 32.93396,
    "googleMapsUrl": "https://maps.google.com/?q=34.66527,32.93396",
    "xp": 170,
    "requiredLevel": 4
  },
  {
    "id": "molos-promenade",
    "nameKey": "places.molos-promenade.name",
    "nameFallback": "Promenada Molos w Limassol",
    "descriptionKey": "places.molos-promenade.description",
    "descriptionFallback": "Nadmorski park z palmami, rzeźbami i kawiarniami – ulubione miejsce spacerów mieszkańców Limassol.",
    "badgeKey": "places.molos-promenade.badge",
    "badgeFallback": "Mistrz Promenady",
    "lat": 34.67658,
    "lng": 33.04979,
    "googleMapsUrl": "https://maps.google.com/?q=34.67658,33.04979",
    "xp": 130,
    "requiredLevel": 2
  },
  {
    "id": "amathus-ruins",
    "nameKey": "places.amathus-ruins.name",
    "nameFallback": "Ruiny starożytnego Amathus",
    "descriptionKey": "places.amathus-ruins.description",
    "descriptionFallback": "Pozostałości jednego z królewskich miast Cypru z agorą, świątynią Afrodyty i wczesnochrześcijańską bazyliką.",
    "badgeKey": "places.amathus-ruins.badge",
    "badgeFallback": "Kurator Amathus",
    "lat": 34.7125,
    "lng": 33.14167,
    "googleMapsUrl": "https://maps.google.com/?q=34.71250,33.14167",
    "xp": 180,
    "requiredLevel": 5
  },
  {
    "id": "limassol-castle",
    "nameKey": "places.limassol-castle.name",
    "nameFallback": "Zamek Limassol (Muzeum Średniowiecza)",
    "descriptionKey": "places.limassol-castle.description",
    "descriptionFallback": "Kamienny zamek w sercu starego miasta, dziś mieszczący muzeum średniowiecznych artefaktów.",
    "badgeKey": "places.limassol-castle.badge",
    "badgeFallback": "Strażnik Limassol",
    "lat": 34.6722,
    "lng": 33.0415,
    "googleMapsUrl": "https://maps.google.com/?q=34.67220,33.04150",
    "xp": 160,
    "requiredLevel": 3
  },
  {
    "id": "saint-lazarus-church",
    "nameKey": "places.saint-lazarus-church.name",
    "nameFallback": "Kościół św. Łazarza w Larnace",
    "descriptionKey": "places.saint-lazarus-church.description",
    "descriptionFallback": "Kamienna świątynia z IX wieku, zbudowana nad grobem św. Łazarza i słynąca z bogatego ikonostasu.",
    "badgeKey": "places.saint-lazarus-church.badge",
    "badgeFallback": "Opiekun Relikwii",
    "lat": 34.9125,
    "lng": 33.6333,
    "googleMapsUrl": "https://maps.google.com/?q=34.91250,33.63330",
    "xp": 150,
    "requiredLevel": 3
  },
  {
    "id": "larnaca-salt-lake-hala-sultan",
    "nameKey": "places.larnaca-salt-lake-hala-sultan.name",
    "nameFallback": "Słone Jezioro Larnaka i Hala Sultan Tekke",
    "descriptionKey": "places.larnaca-salt-lake-hala-sultan.description",
    "descriptionFallback": "Zimowe flamingi i mistyczny meczet Hala Sultan Tekke tworzą wyjątkowy krajobraz nad słonym jeziorem.",
    "badgeKey": "places.larnaca-salt-lake-hala-sultan.badge",
    "badgeFallback": "Obserwator Flamingów",
    "lat": 34.8853,
    "lng": 33.6102,
    "googleMapsUrl": "https://maps.google.com/?q=34.88530,33.61020",
    "xp": 140,
    "requiredLevel": 3
  },
  {
    "id": "finikoudes-beach",
    "nameKey": "places.finikoudes-beach.name",
    "nameFallback": "Plaża Finikoudes w Larnace",
    "descriptionKey": "places.finikoudes-beach.description",
    "descriptionFallback": "Miejska plaża z palmową promenadą, tętniącymi życiem kawiarniami i łagodnym wejściem do morza.",
    "badgeKey": "places.finikoudes-beach.badge",
    "badgeFallback": "Mistrz Palm",
    "lat": 34.913895,
    "lng": 33.638418,
    "googleMapsUrl": "https://maps.google.com/?q=34.913895,33.638418",
    "xp": 115,
    "requiredLevel": 1
  },
  {
    "id": "chirokitia-archaeological-site",
    "nameKey": "places.chirokitia-archaeological-site.name",
    "nameFallback": "Stanowisko archeologiczne Chirokitia",
    "descriptionKey": "places.chirokitia-archaeological-site.description",
    "descriptionFallback": "Neolityczna osada wpisana na listę UNESCO z rekonstrukcjami okrągłych kamiennych chat.",
    "badgeKey": "places.chirokitia-archaeological-site.badge",
    "badgeFallback": "Pionier Neolitu",
    "lat": 34.79672,
    "lng": 33.34372,
    "googleMapsUrl": "https://maps.google.com/?q=34.79672,33.34372",
    "xp": 200,
    "requiredLevel": 5
  },
  {
    "id": "lefkara-village",
    "nameKey": "places.lefkara-village.name",
    "nameFallback": "Wioska Lefkara",
    "descriptionKey": "places.lefkara-village.description",
    "descriptionFallback": "Górska wioska słynąca z koronek lefkaritiko i srebrnego rękodzieła w kamiennych domach.",
    "badgeKey": "places.lefkara-village.badge",
    "badgeFallback": "Mistrzyni Koronek",
    "lat": 34.867,
    "lng": 33.3,
    "googleMapsUrl": "https://maps.google.com/?q=34.86700,33.30000",
    "xp": 170,
    "requiredLevel": 4
  },
  {
    "id": "nissi-beach",
    "nameKey": "places.nissi-beach.name",
    "nameFallback": "Plaża Nissi (Ayia Napa)",
    "descriptionKey": "places.nissi-beach.description",
    "descriptionFallback": "Jasny piasek, płytka laguna i wysepka Nissi czynią to miejsce ikoną wypoczynku i sportów wodnych.",
    "badgeKey": "places.nissi-beach.badge",
    "badgeFallback": "Łowca Słońca",
    "lat": 34.99,
    "lng": 33.97,
    "googleMapsUrl": "https://maps.google.com/?q=34.99000,33.97000",
    "xp": 120,
    "requiredLevel": 1
  },
  {
    "id": "cape-greco",
    "nameKey": "places.cape-greco.name",
    "nameFallback": "Przylądek Greko (Cape Greco)",
    "descriptionKey": "places.cape-greco.description",
    "descriptionFallback": "Park narodowy z klifami, morskimi jaskiniami i słynnym skalnym Mostem Miłości.",
    "badgeKey": "places.cape-greco.badge",
    "badgeFallback": "Łowca Horyzontów",
    "lat": 35,
    "lng": 34.01667,
    "googleMapsUrl": "https://maps.google.com/?q=35.00000,34.01667",
    "xp": 210,
    "requiredLevel": 8
  },
  {
    "id": "fig-tree-bay",
    "nameKey": "places.fig-tree-bay.name",
    "nameFallback": "Plaża Fig Tree Bay (Protaras)",
    "descriptionKey": "places.fig-tree-bay.description",
    "descriptionFallback": "Lazurowa zatoka ze złotym piaskiem i samotnym drzewem figowym będącym symbolem okolicy.",
    "badgeKey": "places.fig-tree-bay.badge",
    "badgeFallback": "Strażnik Piasków",
    "lat": 35.012567,
    "lng": 34.058549,
    "googleMapsUrl": "https://maps.google.com/?q=35.012567,34.058549",
    "xp": 125,
    "requiredLevel": 1
  },
  {
    "id": "ayia-napa-monastery",
    "nameKey": "places.ayia-napa-monastery.name",
    "nameFallback": "Klasztor Ayia Napa",
    "descriptionKey": "places.ayia-napa-monastery.description",
    "descriptionFallback": "XVII-wieczny klasztor z dziedzińcem i sykomorą, będący duchową oazą gwarnej Ayia Napy.",
    "badgeKey": "places.ayia-napa-monastery.badge",
    "badgeFallback": "Kustosz Monastyrów",
    "lat": 34.989202,
    "lng": 33.999746,
    "googleMapsUrl": "https://maps.google.com/?q=34.989202,33.999746",
    "xp": 160,
    "requiredLevel": 3
  },
  {
    "id": "ayia-napa-sculpture-park",
    "nameKey": "places.ayia-napa-sculpture-park.name",
    "nameFallback": "Park Rzeźb w Ayia Napa",
    "descriptionKey": "places.ayia-napa-sculpture-park.description",
    "descriptionFallback": "Plenerowa galeria sztuki z ponad setką rzeźb na tle morza i sąsiedniego parku kaktusów.",
    "badgeKey": "places.ayia-napa-sculpture-park.badge",
    "badgeFallback": "Kurator Rzeźb",
    "lat": 34.985077,
    "lng": 34.01929,
    "googleMapsUrl": "https://maps.google.com/?q=34.985077,34.019290",
    "xp": 150,
    "requiredLevel": 3
  },
  {
    "id": "troodos-olympos",
    "nameKey": "places.troodos-olympos.name",
    "nameFallback": "Góra Olimp (Olimbos)",
    "descriptionKey": "places.troodos-olympos.description",
    "descriptionFallback": "Najwyższy szczyt Cypru z letnim szlakiem Artemis i zimowymi stokami narciarskimi.",
    "badgeKey": "places.troodos-olympos.badge",
    "badgeFallback": "Zdobywca Troodos",
    "lat": 34.93639,
    "lng": 32.86333,
    "googleMapsUrl": "https://maps.google.com/?q=34.93639,32.86333",
    "xp": 200,
    "requiredLevel": 7
  },
  {
    "id": "kykkos-monastery",
    "nameKey": "places.kykkos-monastery.name",
    "nameFallback": "Klasztor Kykkos",
    "descriptionKey": "places.kykkos-monastery.description",
    "descriptionFallback": "Najbogatszy klasztor Cypru z mozaikami, złotymi ikonami i muzeum sakralnym.",
    "badgeKey": "places.kykkos-monastery.badge",
    "badgeFallback": "Opiekun Dziedzictwa",
    "lat": 34.98334,
    "lng": 32.741299,
    "googleMapsUrl": "https://maps.google.com/?q=34.98334,32.741299",
    "xp": 190,
    "requiredLevel": 5
  },
  {
    "id": "omodos-village",
    "nameKey": "places.omodos-village.name",
    "nameFallback": "Wioska Omodos (centrum)",
    "descriptionKey": "places.omodos-village.description",
    "descriptionFallback": "Historyczna wioska z klasztorem Św. Krzyża, brukowanymi uliczkami i lokalnym rękodziełem.",
    "badgeKey": "places.omodos-village.badge",
    "badgeFallback": "Sommelier Omodos",
    "lat": 34.84926,
    "lng": 32.80986,
    "googleMapsUrl": "https://maps.google.com/?q=34.84926,32.80986",
    "xp": 170,
    "requiredLevel": 4
  },
  {
    "id": "kakopetria-village",
    "nameKey": "places.kakopetria-village.name",
    "nameFallback": "Wioska Kakopetria",
    "descriptionKey": "places.kakopetria-village.description",
    "descriptionFallback": "Górska miejscowość z tradycyjnymi domami i strumieniem, idealna na spacery po Troodos.",
    "badgeKey": "places.kakopetria-village.badge",
    "badgeFallback": "Strażnik Górskich Wiosek",
    "lat": 34.9876,
    "lng": 32.9015,
    "googleMapsUrl": "https://maps.google.com/?q=34.98760,32.90150",
    "xp": 160,
    "requiredLevel": 3
  },
  {
    "id": "caledonia-waterfall",
    "nameKey": "places.caledonia-waterfall.name",
    "nameFallback": "Wodospad Kaledonia (Kalidonia)",
    "descriptionKey": "places.caledonia-waterfall.description",
    "descriptionFallback": "Jedna z najwyższych kaskad Cypru ukryta w cienistym wąwozie w pobliżu miejscowości Platres.",
    "badgeKey": "places.caledonia-waterfall.badge",
    "badgeFallback": "Poskramiacz Wodospadów",
    "lat": 34.90298,
    "lng": 32.86989,
    "googleMapsUrl": "https://maps.google.com/?q=34.90298,32.86989",
    "xp": 180,
    "requiredLevel": 4
  },
  {
    "id": "kyrenia-old-harbour",
    "nameKey": "places.kyrenia-old-harbour.name",
    "nameFallback": "Stary port w Kyrenii (Girne)",
    "descriptionKey": "places.kyrenia-old-harbour.description",
    "descriptionFallback": "Zabytkowy port z tawernami i jachtami u stóp średniowiecznego zamku, tętniący wieczornym życiem.",
    "badgeKey": "places.kyrenia-old-harbour.badge",
    "badgeFallback": "Kapitan Morza Śródziemnego",
    "lat": 35.34189,
    "lng": 33.320442,
    "googleMapsUrl": "https://maps.google.com/?q=35.34189,33.320442",
    "xp": 150,
    "requiredLevel": 2
  },
  {
    "id": "kyrenia-castle",
    "nameKey": "places.kyrenia-castle.name",
    "nameFallback": "Zamek w Kyrenii",
    "descriptionKey": "places.kyrenia-castle.description",
    "descriptionFallback": "Wenecka forteca z muzeum wraku statku i widokami na port oraz Morze Śródziemne.",
    "badgeKey": "places.kyrenia-castle.badge",
    "badgeFallback": "Strażnik Bastionu",
    "lat": 35.34202,
    "lng": 33.32191,
    "googleMapsUrl": "https://maps.google.com/?q=35.34202,33.32191",
    "xp": 180,
    "requiredLevel": 4
  },
  {
    "id": "st-hilarion-castle",
    "nameKey": "places.st-hilarion-castle.name",
    "nameFallback": "Zamek św. Hilariona",
    "descriptionKey": "places.st-hilarion-castle.description",
    "descriptionFallback": "Górska twierdza rozsiana po trzech poziomach skał, z legendarnymi widokami na wybrzeże.",
    "badgeKey": "places.st-hilarion-castle.badge",
    "badgeFallback": "Rycerz Gór Kyrenii",
    "lat": 35.312485,
    "lng": 33.281364,
    "googleMapsUrl": "https://maps.google.com/?q=35.312485,33.281364",
    "xp": 220,
    "requiredLevel": 6
  },
  {
    "id": "famagusta-old-town",
    "nameKey": "places.famagusta-old-town.name",
    "nameFallback": "Stare miasto Famagusta (Gazimağusa)",
    "descriptionKey": "places.famagusta-old-town.description",
    "descriptionFallback": "Ufortyfikowane miasto z weneckimi murami, katedrą św. Mikołaja i zamkiem Othello przy porcie.",
    "badgeKey": "places.famagusta-old-town.badge",
    "badgeFallback": "Kronikarz Famagusty",
    "lat": 35.125,
    "lng": 33.94167,
    "googleMapsUrl": "https://maps.google.com/?q=35.12500,33.94167",
    "xp": 210,
    "requiredLevel": 6
  },
  {
    "id": "karpaz-golden-beach",
    "nameKey": "places.karpaz-golden-beach.name",
    "nameFallback": "Złota Plaża (Golden Beach) na Półwyspie Karpaz",
    "descriptionKey": "places.karpaz-golden-beach.description",
    "descriptionFallback": "Dzika, szeroka plaża o drobnym piasku, otoczona wydmami i stadami dzikich osłów.",
    "badgeKey": "places.karpaz-golden-beach.badge",
    "badgeFallback": "Strażnik Wydm",
    "lat": 35.63889,
    "lng": 34.54389,
    "googleMapsUrl": "https://maps.google.com/?q=35.63889,34.54389",
    "xp": 230,
    "requiredLevel": 7
  },
  {
    "id": "zenobia-wreck",
    "nameKey": "places.zenobia-wreck.name",
    "nameFallback": "Wrak Zenobii (Zenobia Wreck)",
    "descriptionKey": "places.zenobia-wreck.description",
    "descriptionFallback": "Wrak promu zatopiony u wybrzeża Larnaki, popularny obiekt do nurkowania.",
    "badgeKey": "places.zenobia-wreck.badge",
    "badgeFallback": "Mistrz Wraków",
    "lat": 34.9,
    "lng": 33.633,
    "googleMapsUrl": "https://maps.google.com/?q=34.90000,33.63300",
    "xp": 240,
    "requiredLevel": 8
  },
  {
    "id": "avakas-gorge",
    "nameKey": "places.avakas-gorge.name",
    "nameFallback": "Wąwóz Avakas (Avakas Gorge)",
    "descriptionKey": "places.avakas-gorge.description",
    "descriptionFallback": "Wąwóz z dramatycznymi formacjami skalnymi i ścieżkami trekkingowymi na półwyspie Akamas.",
    "badgeKey": "places.avakas-gorge.badge",
    "badgeFallback": "Wędrowiec Wąwozów",
    "lat": 34.9935,
    "lng": 32.355,
    "googleMapsUrl": "https://maps.google.com/?q=34.99350,32.35500",
    "xp": 200,
    "requiredLevel": 6
  },
  {
    "id": "aphrodites-baths",
    "nameKey": "places.aphrodites-baths.name",
    "nameFallback": "Łaźnie Afrodyty (Baths of Aphrodite)",
    "descriptionKey": "places.aphrodites-baths.description",
    "descriptionFallback": "Mały, romantyczny basen naturalny na półwyspie Akamas, związany z legendą Afrodyty.",
    "badgeKey": "places.aphrodites-baths.badge",
    "badgeFallback": "Strażnik Legend Afrodyty",
    "lat": 35.014,
    "lng": 32.367,
    "googleMapsUrl": "https://maps.google.com/?q=35.01400,32.36700",
    "xp": 150,
    "requiredLevel": 3
  },
  {
    "id": "polis-latchi-marina",
    "nameKey": "places.polis-latchi-marina.name",
    "nameFallback": "Polis i Marina Latchi",
    "descriptionKey": "places.polis-latchi-marina.description",
    "descriptionFallback": "Nadmorskie miasteczko z mariną, będące punktem wypadowym na rejsy do Błękitnej Laguny.",
    "badgeKey": "places.polis-latchi-marina.badge",
    "badgeFallback": "Kapitan Laguny",
    "lat": 35.038,
    "lng": 32.43,
    "googleMapsUrl": "https://maps.google.com/?q=35.03800,32.43000",
    "xp": 140,
    "requiredLevel": 2
  },
  {
    "id": "st-hilarion-vantage-point",
    "nameKey": "places.st-hilarion-vantage-point.name",
    "nameFallback": "Punkt widokowy zamku św. Hilariona",
    "descriptionKey": "places.st-hilarion-vantage-point.description",
    "descriptionFallback": "Punkt widokowy u stóp zamku św. Hilariona z szeroką panoramą wybrzeża Kyrenii.",
    "badgeKey": "places.st-hilarion-vantage-point.badge",
    "badgeFallback": "Łowca Horyzontów",
    "lat": 35.31,
    "lng": 33.28,
    "googleMapsUrl": "https://maps.google.com/?q=35.31000,33.28000",
    "xp": 160,
    "requiredLevel": 4
  },
  {
    "id": "buffavento-castle",
    "nameKey": "places.buffavento-castle.name",
    "nameFallback": "Zamek Buffavento",
    "descriptionKey": "places.buffavento-castle.description",
    "descriptionFallback": "Ruiny zamku na wzgórzu nad Morzem Śródziemnym, niedaleko twierdzy św. Hilariona.",
    "badgeKey": "places.buffavento-castle.badge",
    "badgeFallback": "Strażnik Buffavento",
    "lat": 35.33,
    "lng": 33.29,
    "googleMapsUrl": "https://maps.google.com/?q=35.33000,33.29000",
    "xp": 210,
    "requiredLevel": 6
  },
  {
    "id": "lania-village",
    "nameKey": "places.lania-village.name",
    "nameFallback": "Wioska Lania",
    "descriptionKey": "places.lania-village.description",
    "descriptionFallback": "Malownicza osada u podnóża Troodos, znana z winiarstwa, galerii i spokojnej atmosfery.",
    "badgeKey": "places.lania-village.badge",
    "badgeFallback": "Artysta z Lanii",
    "lat": 34.78,
    "lng": 32.9,
    "googleMapsUrl": "https://maps.google.com/?q=34.78000,32.90000",
    "xp": 120,
    "requiredLevel": 1
  },
  {
    "id": "trooditissa-monastery",
    "nameKey": "places.trooditissa-monastery.name",
    "nameFallback": "Klasztor Trooditissa",
    "descriptionKey": "places.trooditissa-monastery.description",
    "descriptionFallback": "Górski monastyr w masywie Troodos, otoczony lasami i pełen ikon oraz pielgrzymów.",
    "badgeKey": "places.trooditissa-monastery.badge",
    "badgeFallback": "Pielgrzym Trooditissa",
    "lat": 34.916,
    "lng": 32.819,
    "googleMapsUrl": "https://maps.google.com/?q=34.91600,32.81900",
    "xp": 170,
    "requiredLevel": 4
  },
  {
    "id": "soli-ancient-site",
    "nameKey": "places.soli-ancient-site.name",
    "nameFallback": "Starożytne miasto Soli",
    "descriptionKey": "places.soli-ancient-site.description",
    "descriptionFallback": "Ruiny antycznego miasta z amfiteatrem i pozostałościami portu w pobliżu Famagusty.",
    "badgeKey": "places.soli-ancient-site.badge",
    "badgeFallback": "Archeolog Soli",
    "lat": 35.144,
    "lng": 33.897,
    "googleMapsUrl": "https://maps.google.com/?q=35.14400,33.89700",
    "xp": 180,
    "requiredLevel": 5
  },
  {
    "id": "limassol-municipal-aquarium",
    "nameKey": "places.limassol-municipal-aquarium.name",
    "nameFallback": "Miejskie Akwarium w Limassol",
    "descriptionKey": "places.limassol-municipal-aquarium.description",
    "descriptionFallback": "Kameralne akwarium edukacyjne prezentujące lokalną faunę morską i programy ochronne.",
    "badgeKey": "places.limassol-municipal-aquarium.badge",
    "badgeFallback": "Opiekun Raf Limassol",
    "lat": 34.707,
    "lng": 33.069,
    "googleMapsUrl": "https://maps.google.com/?q=34.70700,33.06900",
    "xp": 110,
    "requiredLevel": 1
  },
  {
    "id": "dasoudi-beach",
    "nameKey": "places.dasoudi-beach.name",
    "nameFallback": "Plaża Dasoudi",
    "descriptionKey": "places.dasoudi-beach.description",
    "descriptionFallback": "Piaszczysta plaża w Limassol z nadbrzeżnym parkiem, ścieżkami spacerowymi i terenami zielonymi.",
    "badgeKey": "places.dasoudi-beach.badge",
    "badgeFallback": "Miłośnik Dasoudi",
    "lat": 34.68,
    "lng": 33.035,
    "googleMapsUrl": "https://maps.google.com/?q=34.68000,33.03500",
    "xp": 115,
    "requiredLevel": 1
  },
  {
    "id": "governors-beach",
    "nameKey": "places.governors-beach.name",
    "nameFallback": "governors-beach",
    "descriptionKey": "places.governors-beach.description",
    "descriptionFallback": "",
    "badgeKey": "places.governors-beach.badge",
    "badgeFallback": "Odkrywca Klifów",
    "lat": 34.725,
    "lng": 33.1,
    "googleMapsUrl": "https://maps.google.com/?q=34.72500,33.10000",
    "xp": 130,
    "requiredLevel": 2
  },
  {
    "id": "macronissos-beach",
    "nameKey": "places.macronissos-beach.name",
    "nameFallback": "Plaża Macronissos",
    "descriptionKey": "places.macronissos-beach.description",
    "descriptionFallback": "Zatoka z jasnym piaskiem i spokojnymi wodami w pobliżu Ayia Napy, idealna na rodzinny wypoczynek.",
    "badgeKey": "places.macronissos-beach.badge",
    "badgeFallback": "Plażowicz Macronissos",
    "lat": 34.9975,
    "lng": 34.02,
    "googleMapsUrl": "https://maps.google.com/?q=34.99750,34.02000",
    "xp": 125,
    "requiredLevel": 1
  },
  {
    "id": "yeroskipou-town",
    "nameKey": "places.yeroskipou-town.name",
    "nameFallback": "Yeroskipou (Kouklia)",
    "descriptionKey": "places.yeroskipou-town.description",
    "descriptionFallback": "Miasteczko niedaleko Pafos z kościołem Agios Georgios i słynnymi słodyczami pastelli.",
    "badgeKey": "places.yeroskipou-town.badge",
    "badgeFallback": "Smakosz Pastelli",
    "lat": 34.715,
    "lng": 32.49,
    "googleMapsUrl": "https://maps.google.com/?q=34.71500,32.49000",
    "xp": 135,
    "requiredLevel": 2
  },
  {
    "id": "agios-neophytos-monastery",
    "nameKey": "places.agios-neophytos-monastery.name",
    "nameFallback": "Klasztor Agios Neophytos",
    "descriptionKey": "places.agios-neophytos-monastery.description",
    "descriptionFallback": "Pustelniczy klasztor wykuty w skale, zdobiony malowidłami założonymi przez św. Neofitosa.",
    "badgeKey": "places.agios-neophytos-monastery.badge",
    "badgeFallback": "Kronikarz Neofitosa",
    "lat": 34.822,
    "lng": 32.389,
    "googleMapsUrl": "https://maps.google.com/?q=34.82200,32.38900",
    "xp": 175,
    "requiredLevel": 4
  },
  {
    "id": "vouni-ancient-house",
    "nameKey": "places.vouni-ancient-house.name",
    "nameFallback": "Starożytny dom zgromadzeń w Vouni",
    "descriptionKey": "places.vouni-ancient-house.description",
    "descriptionFallback": "Archeologiczne ruiny na wzgórzu Vouni z widokiem na zatoki i dawne królewskie rezydencje.",
    "badgeKey": "places.vouni-ancient-house.badge",
    "badgeFallback": "Strażnik Vouni",
    "lat": 34.8,
    "lng": 32.583,
    "googleMapsUrl": "https://maps.google.com/?q=34.80000,32.58300",
    "xp": 190,
    "requiredLevel": 5
  },
  {
    "id": "nicosia-archaeological-museum",
    "nameKey": "places.nicosia-archaeological-museum.name",
    "nameFallback": "Muzeum Archeologiczne w Nikozji",
    "descriptionKey": "places.nicosia-archaeological-museum.description",
    "descriptionFallback": "Muzeum ukazujące dzieje Cypru od prehistorii po średniowiecze z bogatą kolekcją artefaktów.",
    "badgeKey": "places.nicosia-archaeological-museum.badge",
    "badgeFallback": "Kurator Nikozji",
    "lat": 35.171,
    "lng": 33.365,
    "googleMapsUrl": "https://maps.google.com/?q=35.17100,33.36500",
    "xp": 160,
    "requiredLevel": 3
  },
  {
    "id": "buyuk-han",
    "nameKey": "places.buyuk-han.name",
    "nameFallback": "Büyük Han w Nikozji",
    "descriptionKey": "places.buyuk-han.description",
    "descriptionFallback": "Otoczony dziedziniec karawanseraj z czasów osmańskich, pełen warsztatów rękodzieła i kawiarni.",
    "badgeKey": "places.buyuk-han.badge",
    "badgeFallback": "Kupiec Han",
    "lat": 35.176,
    "lng": 33.364,
    "googleMapsUrl": "https://maps.google.com/?q=35.17600,33.36400",
    "xp": 150,
    "requiredLevel": 3
  },
  {
    "id": "ledra-street",
    "nameKey": "places.ledra-street.name",
    "nameFallback": "Ulica i Brama Ledra",
    "descriptionKey": "places.ledra-street.description",
    "descriptionFallback": "Jedna z głównych ulic Starej Nikozji prowadząca przez Zieloną Linię między południem a północą.",
    "badgeKey": "places.ledra-street.badge",
    "badgeFallback": "Wędrowiec Ledra",
    "lat": 35.1765,
    "lng": 33.3605,
    "googleMapsUrl": "https://maps.google.com/?q=35.17650,33.36050",
    "xp": 120,
    "requiredLevel": 1
  },
  {
    "id": "eleftheria-square",
    "nameKey": "places.eleftheria-square.name",
    "nameFallback": "Plac Eleftheria (Plac Wolności)",
    "descriptionKey": "places.eleftheria-square.description",
    "descriptionFallback": "Nowoczesny plac w Nikozji projektu Zahy Hadid, łączący historyczne i współczesne warstwy miasta.",
    "badgeKey": "places.eleftheria-square.badge",
    "badgeFallback": "Odkrywca Eleftherii",
    "lat": 35.173,
    "lng": 33.366,
    "googleMapsUrl": "https://maps.google.com/?q=35.17300,33.36600",
    "xp": 125,
    "requiredLevel": 1
  },
  {
    "id": "anexartisias-street",
    "nameKey": "places.anexartisias-street.name",
    "nameFallback": "Ulica Anexartisias w Limassol",
    "descriptionKey": "places.anexartisias-street.description",
    "descriptionFallback": "Główna ulica handlowa Limassol, ulubiona przez mieszkańców i turystów na zakupy oraz kawiarnie.",
    "badgeKey": "places.anexartisias-street.badge",
    "badgeFallback": "Łowca Witryn",
    "lat": 34.7073,
    "lng": 33.0214,
    "googleMapsUrl": "https://maps.google.com/?q=34.70730,33.02140",
    "xp": 115,
    "requiredLevel": 1
  },
  {
    "id": "fasouri-watermania",
    "nameKey": "places.fasouri-watermania.name",
    "nameFallback": "Park wodny Fasouri Watermania",
    "descriptionKey": "places.fasouri-watermania.description",
    "descriptionFallback": "Największy park wodny na Cyprze z licznymi zjeżdżalniami, basenami tematycznymi i strefami relaksu.",
    "badgeKey": "places.fasouri-watermania.badge",
    "badgeFallback": "Mistrz Zjeżdżalni",
    "lat": 34.682,
    "lng": 33.013,
    "googleMapsUrl": "https://maps.google.com/?q=34.68200,33.01300",
    "xp": 180,
    "requiredLevel": 4
  },
  {
    "id": "akamas-national-park",
    "nameKey": "places.akamas-national-park.name",
    "nameFallback": "Park Narodowy Akamas",
    "descriptionKey": "places.akamas-national-park.description",
    "descriptionFallback": "Rozległy obszar dzikiej natury z punktami widokowymi, szlakami i miejscami lęgowymi żółwi.",
    "badgeKey": "places.akamas-national-park.badge",
    "badgeFallback": "Strażnik Akamas",
    "lat": 35.041,
    "lng": 32.375,
    "googleMapsUrl": "https://maps.google.com/?q=35.04100,32.37500",
    "xp": 230,
    "requiredLevel": 7
  },
  {
    "id": "panagia-kykkos-viewpoint",
    "nameKey": "places.panagia-kykkos-viewpoint.name",
    "nameFallback": "Punkt widokowy klasztoru Panagia Kykkos",
    "descriptionKey": "places.panagia-kykkos-viewpoint.description",
    "descriptionFallback": "Wysoko położony punkt przy klasztorze Kykkos z panoramicznym widokiem na góry Troodos.",
    "badgeKey": "places.panagia-kykkos-viewpoint.badge",
    "badgeFallback": "Pielgrzym Kykkos",
    "lat": 34.991,
    "lng": 32.741,
    "googleMapsUrl": "https://maps.google.com/?q=34.99100,32.74100",
    "xp": 220,
    "requiredLevel": 7
  },
  {
    "id": "troodos-square",
    "nameKey": "places.troodos-square.name",
    "nameFallback": "Plac Troodos",
    "descriptionKey": "places.troodos-square.description",
    "descriptionFallback": "Centralny punkt gór Troodos z bazą wypadową na szlaki i zimową stacją narciarską.",
    "badgeKey": "places.troodos-square.badge",
    "badgeFallback": "Odkrywca Troodos",
    "lat": 34.95,
    "lng": 32.87,
    "googleMapsUrl": "https://maps.google.com/?q=34.95000,32.87000",
    "xp": 140,
    "requiredLevel": 2
  },
  {
    "id": "avakas-gorge-west-entrance",
    "nameKey": "places.avakas-gorge-west-entrance.name",
    "nameFallback": "Wąwóz Avakas – wejście zachodnie",
    "descriptionKey": "places.avakas-gorge-west-entrance.description",
    "descriptionFallback": "Alternatywne wejście do wąwozu Avakas, oferujące spokojniejszy trekking i inne formacje skalne.",
    "badgeKey": "places.avakas-gorge-west-entrance.badge",
    "badgeFallback": "Tropiciel Avakas",
    "lat": 35.0005,
    "lng": 32.35,
    "googleMapsUrl": "https://maps.google.com/?q=35.00050,32.35000",
    "xp": 190,
    "requiredLevel": 5
  },
  {
    "id": "cape-greco-sea-caves",
    "nameKey": "places.cape-greco-sea-caves.name",
    "nameFallback": "Jaskinie morskie Cape Greco",
    "descriptionKey": "places.cape-greco-sea-caves.description",
    "descriptionFallback": "Spektakularne jaskinie morskie na klifach Cape Greco, dostępne łodzią, kajakiem lub ze snorkelem.",
    "badgeKey": "places.cape-greco-sea-caves.badge",
    "badgeFallback": "Poszukiwacz Jaskiń",
    "lat": 34.9965,
    "lng": 34.025,
    "googleMapsUrl": "https://maps.google.com/?q=34.99650,34.02500",
    "xp": 200,
    "requiredLevel": 6
  },
  {
    "id": "cyprus-museum",
    "nameKey": "places.cyprus-museum.name",
    "nameFallback": "Cyprus Museum w Nikozji",
    "descriptionKey": "places.cyprus-museum.description",
    "descriptionFallback": "Główne muzeum archeologiczne Cypru z kolekcją obejmującą wszystkie epoki historyczne.",
    "badgeKey": "places.cyprus-museum.badge",
    "badgeFallback": "Strażnik Dziedzictwa",
    "lat": 35.172,
    "lng": 33.3655,
    "googleMapsUrl": "https://maps.google.com/?q=35.17200,33.36550",
    "xp": 170,
    "requiredLevel": 4
  }
];
