import fs from 'node:fs';
import vm from 'node:vm';

// Generated by the disposable local PG16 gate, never a production payload.
const fixture = () => JSON.parse(fs.readFileSync('tests/integration/fixtures/hotels-v2-114492-synthetic-workspace.json', 'utf8'));
function load(rpc = jest.fn()): any {
  const ctx: any = { console, TextEncoder, window: { getSupabase: () => ({ rpc }) } };
  for (const file of ['admin/hotels-v2-workspace-core.js', 'js/hotels-v2-partner-workspace-core.js', 'js/hotels-v2-partner-workspace-repository.js']) {
    vm.runInNewContext(fs.readFileSync(file, 'utf8'), ctx, { filename: file });
  }
  return { core: ctx.HotelsV2PartnerWorkspaceCore, repository: ctx.HotelsV2PartnerWorkspaceRepository };
}
const scope = () => { const d = fixture(); return [d.partner.id, d.hotel_id, d.availability.from, d.availability.to]; };

describe('114492 exact post-conversion Partner workspace', () => {
  test('real synthetic DTO routes once to 114492 with complete projections and no fallback', async () => {
    const dto = fixture(); const rpc = jest.fn().mockResolvedValue({ data: dto, error: null });
    const { repository } = load(rpc);
    expect(await repository.getWorkspace(...scope())).toEqual(dto);
    expect(rpc.mock.calls).toEqual([['hotel_v2_partner_get_workspace_114492', {
      p_partner_id: dto.partner.id, p_hotel_id: dto.hotel_id, p_from: dto.availability.from, p_to: dto.availability.to,
    }]]);
  });
  test.each([
    ['old contract', (d: any) => { d.contract_version = 'hotels_v2_h3_2b_partner_workspace_114489_v1'; }],
    ['foreign Partner', (d: any) => { d.partner.id = '22222222-2222-4222-8222-222222222222'; }],
    ['legacy architecture', (d: any) => { d.property.architecture_version = 'legacy'; }],
    ['missing receipt', (d: any) => { d.architecture_successor.conversion_receipt_present = false; }],
    ['public booking', (d: any) => { d.architecture_successor.public_booking_enabled = true; }],
    ['scope elevation', (d: any) => { d.partner.role = 'admin'; }],
    ['PII smuggling', (d: any) => { d.email = 'private@example.invalid'; }],
    ['missing pricing', (d: any) => { d.pricing = null; }],
    ['missing availability', (d: any) => { d.availability = null; }],
    ['staff onboarding elevation', (d: any) => { d.partner.role = 'staff'; d.stripe_connection.onboarding_authorized = true; d.stripe_connection.can_connect = true; }],
    ['public change', (d: any) => { d.public_change = true; }],
  ])('rejects %s', (_name, mutate) => {
    const d = fixture(); (mutate as (d: any) => void)(d);
    expect(() => load().core.validateWorkspace114492(d)).toThrow();
  });
  test.each([404, 401, 403, 500])('fails closed without legacy retry on HTTP %i', async status => {
    const rpc = jest.fn().mockResolvedValue({ data: null, status, error: { code: status === 404 ? 'PGRST202' : '42501', message: 'Could not find the function public.hotel_v2_partner_get_workspace_114492 in the schema cache' } });
    await expect(load(rpc).repository.getWorkspace(...scope())).rejects.toMatchObject({ isWorkspace114492NotInstalled: status === 404 });
    expect(rpc).toHaveBeenCalledTimes(1);
  });
  test('scoped staff retains permitted reads but cannot connect Stripe', () => {
    const d = fixture(); d.partner.role = 'staff';
    expect(load().core.validateWorkspace114492(d).stripe_connection.onboarding_authorized).toBe(false);
  });
});
