BEGIN;
SET TRANSACTION READ ONLY;
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
-- Successor-aware copy of the accepted 114420 gate, after exact 114416 reconciliation.
-- All original 109 scalar conditions remain unchanged; only two evolved source pins
-- and three additional fail-closed reconciliation conditions are different.
-- Exact 114420 file SHA256:
-- 7026d08e220887f4f71553c3d7e53384f89b23bbc686ae3bd51a24e7b2aee879
-- NOT EXECUTED. This is a diagnostic, not permission to install.
-- Fixed Partner Get reuses the same workspace token as 114415 Partner Preview.
-- Composite inputs: Admin-C token, commission policy, ordered exact-date prices.
-- Compatibility requires immutable workspace lineage and exact helper/security pins.
-- EXTERNAL HUMAN EVIDENCE ONLY: recovery 08 Sep 2026 05:38:06 UTC, COMPLETED, Restore available.
-- POST_114415_RECOVERY_POINT_CONFIRMED=YES; SQL does not prove backup state.
-- Snapshot checks are point-in-time only; no locks protecting a later write.
-- All embedded query_to_xml strings are fixed, scalar SELECTs. No user SQL.
-- Missing relations/functions yield a named prerequisite failure, not fabricated zero.
-- Errors inside present helpers abort read-only execution and cannot mean PASS.
-- No statement_timeout override; no mutation RPC invocation.
WITH
pins(signature,source_sha256,volatility,security_definer,configuration,authenticated_execute) AS (
  VALUES
  ('public.hotel_v2_seven_arches_independent_pricing_topology_is_exact()','8657d02bb8ae500ddfa366a84d1dfee6bf9f425f529cba30269522a8d9485df2','s',true,ARRAY['search_path=pg_catalog, public']::text[],false),
  ('public.hotel_v2_seven_arches_reviewed_pricing_receipt_chain_is_exact()','b3693dead7fbbe9029a9503e361d085e2c21ef0fef025d150149ef013f249873','s',true,ARRAY['search_path=pg_catalog, public']::text[],false),
  ('public.hotel_v2_seven_arches_reviewed_pricing_current_state()','1374c443a68b4eefbfb361021c0a8d24b51a3200a5995d87a8d7aa114f0835d1','s',true,ARRAY['search_path=pg_catalog, public']::text[],false),
  ('public.hotel_v2_seven_arches_reviewed_pricing_oracle()','50fee36eb4e4c7a11ad0baf0188a9f2042bde3678c5d835b3e8b7ece992ebfef','s',true,ARRAY['search_path=pg_catalog, public']::text[],false),
  ('public.hotel_v2_admin_c_pricing_control_snapshot(uuid)','3f954c525277c771c3009e9ca1fbbf6c68776904f40bc70978d01f7f10a060b0','s',true,ARRAY['search_path=pg_catalog, public']::text[],false),
  ('public.hotel_v2_h3_2b_access_snapshot(uuid,uuid,text)','7f8cb70e2c7034d17f03377cf7ffe3d5648e47dc27800e9ac3542bc95e2bb5b4','s',true,ARRAY['search_path=pg_catalog, public, auth']::text[],false),
  ('public.hotel_v2_partner_workspace_function_lineage_is_exact()','dde4fac2d044a53bb713cced26ca93c8295548c9bde3717d0ea83dc511801a85','s',true,ARRAY['search_path=pg_catalog, public']::text[],false),
  ('public.hotel_v2_h3_2b_exact_price_projection(uuid)','41f8609b712906301ef93e0eb438188ce1989e1114ccea1dcf3f55e1775f438b','s',true,ARRAY['search_path=pg_catalog, public']::text[],false),
  ('public.hotel_v2_h3_2b_commission_policy(uuid)','533a819b7903a4247196955a555a32c4a26b4bea4450814017334c83903ace77','s',true,ARRAY['search_path=pg_catalog, public']::text[],false),
  ('public.hotel_v2_h3_2b_commercial(jsonb,numeric,integer,numeric)','5dec10461b12cec5efb72c9760d7f6126db440107c64af629412034bce0127db','i',true,ARRAY['search_path=pg_catalog']::text[],false),
  ('public.hotel_v2_h3_2b_hash(jsonb)','d60c1f7509fa64b84e52ea9b7cd06d69f295044e76fd450cafda81528c96a828','i',false,ARRAY['search_path=pg_catalog']::text[],false),
  ('public.hotel_v2_h2a_keys_allowed(jsonb,text[])','ad7d11bdbc9f1351e300ceaf9dc0e69b95464b0f8a4b6cd4fbdb179f77ae65e3','i',false,ARRAY['search_path=pg_catalog']::text[],false),
  ('public.hotel_v2_partner_preview_seven_arches_pricing_proposal(jsonb)','4359cc39a9bec782c54f3300fb6c4cf5e53aa552eaa8ee0b540bd678c39f2ce5','v',true,ARRAY['search_path=pg_catalog, public, auth']::text[],true),
  ('public.hotel_v2_partner_submit_seven_arches_pricing_proposal(jsonb,uuid,uuid)','b63c69fbf6c3a376f01259ad56f0a1fc6e4f19ace374ffddbcbebd33fe456bc6','v',true,ARRAY['search_path=pg_catalog, public, auth']::text[],true)
),
pin_results AS MATERIALIZED (
  SELECT e.signature,
    p.oid IS NOT NULL
    AND p.proowner='postgres'::regrole
    AND p.provolatile=e.volatility::"char"
    AND p.prosecdef=e.security_definer
    AND p.proconfig IS NOT DISTINCT FROM e.configuration
    AND encode(sha256(convert_to(p.prosrc,'UTF8')),'hex')=e.source_sha256
    AND has_function_privilege('postgres',p.oid,'EXECUTE')
    AND NOT has_function_privilege(0::oid,p.oid,'EXECUTE')
    AND NOT has_function_privilege('anon',p.oid,'EXECUTE')
    AND has_function_privilege('authenticated',p.oid,'EXECUTE')=e.authenticated_execute
    AND NOT has_function_privilege('service_role',p.oid,'EXECUTE') AS exact,
    jsonb_build_object('exists',p.oid IS NOT NULL,
      'source_exact',encode(sha256(convert_to(p.prosrc,'UTF8')),'hex')=e.source_sha256,
      'owner',pg_get_userbyid(p.proowner),'volatility',p.provolatile,
      'security_definer',p.prosecdef,'configuration',p.proconfig,
      'public_execute',has_function_privilege(0::oid,p.oid,'EXECUTE'),
      'anon_execute',has_function_privilege('anon',p.oid,'EXECUTE'),
      'authenticated_execute',has_function_privilege('authenticated',p.oid,'EXECUTE'),
      'service_role_execute',has_function_privilege('service_role',p.oid,'EXECUTE')
    )::text AS safe_context
  FROM pins e LEFT JOIN pg_proc p ON p.oid=to_regprocedure(e.signature)
),
specs(ordinal,section,leaf_name,expected,required_relations,required_functions,read_query) AS (
  VALUES
  (1,'session','transaction_read_only','on',
    ARRAY[]::text[],ARRAY[]::text[],
    $read1$SELECT (current_setting('transaction_read_only'))::text AS actual$read1$),
  (2,'workspace_contract','partner_pricing_snapshot_contract_compatible','true',
    ARRAY[]::text[],ARRAY['public.hotel_v2_partner_workspace_function_lineage_is_exact()']::text[],
    $read2$SELECT (public.hotel_v2_partner_workspace_function_lineage_is_exact())::text AS actual$read2$),
  (3,'history','recorded_114350','1',
    ARRAY['supabase_migrations.schema_migrations']::text[],ARRAY[]::text[],
    $read3$SELECT ((SELECT count(*) FROM supabase_migrations.schema_migrations WHERE version::text='20260811435000'))::text AS actual$read3$),
  (4,'history','recorded_114360','1',
    ARRAY['supabase_migrations.schema_migrations']::text[],ARRAY[]::text[],
    $read4$SELECT ((SELECT count(*) FROM supabase_migrations.schema_migrations WHERE version::text='20260811436000'))::text AS actual$read4$),
  (5,'history','recorded_114370','1',
    ARRAY['supabase_migrations.schema_migrations']::text[],ARRAY[]::text[],
    $read5$SELECT ((SELECT count(*) FROM supabase_migrations.schema_migrations WHERE version::text='20260811437000'))::text AS actual$read5$),
  (6,'history','recorded_114400','1',
    ARRAY['supabase_migrations.schema_migrations']::text[],ARRAY[]::text[],
    $read6$SELECT ((SELECT count(*) FROM supabase_migrations.schema_migrations WHERE version::text='20260811440000'))::text AS actual$read6$),
  (7,'history','recorded_114405','1',
    ARRAY['supabase_migrations.schema_migrations']::text[],ARRAY[]::text[],
    $read7$SELECT ((SELECT count(*) FROM supabase_migrations.schema_migrations WHERE version::text='20260811440500'))::text AS actual$read7$),
  (8,'history','recorded_114406','1',
    ARRAY['supabase_migrations.schema_migrations']::text[],ARRAY[]::text[],
    $read8$SELECT ((SELECT count(*) FROM supabase_migrations.schema_migrations WHERE version::text='20260811440600'))::text AS actual$read8$),
  (9,'history','recorded_114407','1',
    ARRAY['supabase_migrations.schema_migrations']::text[],ARRAY[]::text[],
    $read9$SELECT ((SELECT count(*) FROM supabase_migrations.schema_migrations WHERE version::text='20260811440700'))::text AS actual$read9$),
  (10,'history','recorded_114410','1',
    ARRAY['supabase_migrations.schema_migrations']::text[],ARRAY[]::text[],
    $read10$SELECT ((SELECT count(*) FROM supabase_migrations.schema_migrations WHERE version::text='20260811441000'))::text AS actual$read10$),
  (11,'history','recorded_114415','1',
    ARRAY['supabase_migrations.schema_migrations']::text[],ARRAY[]::text[],
    $read11$SELECT ((SELECT count(*) FROM supabase_migrations.schema_migrations WHERE version::text='20260811441500'))::text AS actual$read11$),
  (12,'history','recorded_114420','0',
    ARRAY['supabase_migrations.schema_migrations']::text[],ARRAY[]::text[],
    $read12$SELECT ((SELECT count(*) FROM supabase_migrations.schema_migrations WHERE version::text='20260811442000'))::text AS actual$read12$),
  (13,'history','recorded_114425','0',
    ARRAY['supabase_migrations.schema_migrations']::text[],ARRAY[]::text[],
    $read13$SELECT ((SELECT count(*) FROM supabase_migrations.schema_migrations WHERE version::text='20260811442500'))::text AS actual$read13$),
  (14,'history','recorded_114450','0',
    ARRAY['supabase_migrations.schema_migrations']::text[],ARRAY[]::text[],
    $read14$SELECT ((SELECT count(*) FROM supabase_migrations.schema_migrations WHERE version::text='20260811445000'))::text AS actual$read14$),
  (15,'reviewed_foundation','foundation_receipts_count','1',
    ARRAY['public.hotel_seven_arches_reviewed_pricing_foundation_receipts']::text[],ARRAY[]::text[],
    $read15$SELECT ((SELECT count(*) FROM public.hotel_seven_arches_reviewed_pricing_foundation_receipts))::text AS actual$read15$),
  (16,'reviewed_security','foundation_receipts_security','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read16$SELECT (EXISTS(SELECT 1 FROM pg_class c WHERE c.oid=to_regclass('public.hotel_seven_arches_reviewed_pricing_foundation_receipts') AND c.relkind='r' AND c.relpersistence='p' AND c.relowner='postgres'::regrole AND c.relrowsecurity AND NOT c.relforcerowsecurity AND NOT EXISTS(SELECT 1 FROM pg_policy p WHERE p.polrelid=c.oid) AND NOT EXISTS(SELECT 1 FROM aclexplode(coalesce(c.relacl,acldefault('r',c.relowner))) a WHERE a.grantee<>c.relowner) AND NOT EXISTS(SELECT 1 FROM (VALUES(0::oid),('anon'::regrole::oid),('authenticated'::regrole::oid),('service_role'::regrole::oid)) roles(id) CROSS JOIN unnest(ARRAY['SELECT','INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER']) priv(name) WHERE has_table_privilege(roles.id,c.oid,priv.name))))::text AS actual$read16$),
  (17,'reviewed_foundation','evolution_receipts_count','0',
    ARRAY['public.hotel_seven_arches_reviewed_pricing_evolution_receipts']::text[],ARRAY[]::text[],
    $read17$SELECT ((SELECT count(*) FROM public.hotel_seven_arches_reviewed_pricing_evolution_receipts))::text AS actual$read17$),
  (18,'reviewed_security','evolution_receipts_security','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read18$SELECT (EXISTS(SELECT 1 FROM pg_class c WHERE c.oid=to_regclass('public.hotel_seven_arches_reviewed_pricing_evolution_receipts') AND c.relkind='r' AND c.relpersistence='p' AND c.relowner='postgres'::regrole AND c.relrowsecurity AND NOT c.relforcerowsecurity AND NOT EXISTS(SELECT 1 FROM pg_policy p WHERE p.polrelid=c.oid) AND NOT EXISTS(SELECT 1 FROM aclexplode(coalesce(c.relacl,acldefault('r',c.relowner))) a WHERE a.grantee<>c.relowner) AND NOT EXISTS(SELECT 1 FROM (VALUES(0::oid),('anon'::regrole::oid),('authenticated'::regrole::oid),('service_role'::regrole::oid)) roles(id) CROSS JOIN unnest(ARRAY['SELECT','INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER']) priv(name) WHERE has_table_privilege(roles.id,c.oid,priv.name))))::text AS actual$read18$),
  (19,'reviewed_foundation','proposals_count','0',
    ARRAY['public.hotel_seven_arches_reviewed_pricing_proposals']::text[],ARRAY[]::text[],
    $read19$SELECT ((SELECT count(*) FROM public.hotel_seven_arches_reviewed_pricing_proposals))::text AS actual$read19$),
  (20,'reviewed_security','proposals_security','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read20$SELECT (EXISTS(SELECT 1 FROM pg_class c WHERE c.oid=to_regclass('public.hotel_seven_arches_reviewed_pricing_proposals') AND c.relkind='r' AND c.relpersistence='p' AND c.relowner='postgres'::regrole AND c.relrowsecurity AND NOT c.relforcerowsecurity AND NOT EXISTS(SELECT 1 FROM pg_policy p WHERE p.polrelid=c.oid) AND NOT EXISTS(SELECT 1 FROM aclexplode(coalesce(c.relacl,acldefault('r',c.relowner))) a WHERE a.grantee<>c.relowner) AND NOT EXISTS(SELECT 1 FROM (VALUES(0::oid),('anon'::regrole::oid),('authenticated'::regrole::oid),('service_role'::regrole::oid)) roles(id) CROSS JOIN unnest(ARRAY['SELECT','INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER']) priv(name) WHERE has_table_privilege(roles.id,c.oid,priv.name))))::text AS actual$read20$),
  (21,'reviewed_foundation','proposal_items_count','0',
    ARRAY['public.hotel_seven_arches_reviewed_pricing_proposal_items']::text[],ARRAY[]::text[],
    $read21$SELECT ((SELECT count(*) FROM public.hotel_seven_arches_reviewed_pricing_proposal_items))::text AS actual$read21$),
  (22,'reviewed_security','proposal_items_security','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read22$SELECT (EXISTS(SELECT 1 FROM pg_class c WHERE c.oid=to_regclass('public.hotel_seven_arches_reviewed_pricing_proposal_items') AND c.relkind='r' AND c.relpersistence='p' AND c.relowner='postgres'::regrole AND c.relrowsecurity AND NOT c.relforcerowsecurity AND NOT EXISTS(SELECT 1 FROM pg_policy p WHERE p.polrelid=c.oid) AND NOT EXISTS(SELECT 1 FROM aclexplode(coalesce(c.relacl,acldefault('r',c.relowner))) a WHERE a.grantee<>c.relowner) AND NOT EXISTS(SELECT 1 FROM (VALUES(0::oid),('anon'::regrole::oid),('authenticated'::regrole::oid),('service_role'::regrole::oid)) roles(id) CROSS JOIN unnest(ARRAY['SELECT','INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER']) priv(name) WHERE has_table_privilege(roles.id,c.oid,priv.name))))::text AS actual$read22$),
  (23,'reviewed_foundation','admin_reviews_count','0',
    ARRAY['public.hotel_seven_arches_reviewed_pricing_admin_reviews']::text[],ARRAY[]::text[],
    $read23$SELECT ((SELECT count(*) FROM public.hotel_seven_arches_reviewed_pricing_admin_reviews))::text AS actual$read23$),
  (24,'reviewed_security','admin_reviews_security','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read24$SELECT (EXISTS(SELECT 1 FROM pg_class c WHERE c.oid=to_regclass('public.hotel_seven_arches_reviewed_pricing_admin_reviews') AND c.relkind='r' AND c.relpersistence='p' AND c.relowner='postgres'::regrole AND c.relrowsecurity AND NOT c.relforcerowsecurity AND NOT EXISTS(SELECT 1 FROM pg_policy p WHERE p.polrelid=c.oid) AND NOT EXISTS(SELECT 1 FROM aclexplode(coalesce(c.relacl,acldefault('r',c.relowner))) a WHERE a.grantee<>c.relowner) AND NOT EXISTS(SELECT 1 FROM (VALUES(0::oid),('anon'::regrole::oid),('authenticated'::regrole::oid),('service_role'::regrole::oid)) roles(id) CROSS JOIN unnest(ARRAY['SELECT','INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER']) priv(name) WHERE has_table_privilege(roles.id,c.oid,priv.name))))::text AS actual$read24$),
  (25,'reviewed_foundation','transaction_context_count','0',
    ARRAY['public.hotel_seven_arches_reviewed_pricing_transaction_context']::text[],ARRAY[]::text[],
    $read25$SELECT ((SELECT count(*) FROM public.hotel_seven_arches_reviewed_pricing_transaction_context))::text AS actual$read25$),
  (26,'reviewed_security','transaction_context_security','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read26$SELECT (EXISTS(SELECT 1 FROM pg_class c WHERE c.oid=to_regclass('public.hotel_seven_arches_reviewed_pricing_transaction_context') AND c.relkind='r' AND c.relpersistence='p' AND c.relowner='postgres'::regrole AND c.relrowsecurity AND NOT c.relforcerowsecurity AND NOT EXISTS(SELECT 1 FROM pg_policy p WHERE p.polrelid=c.oid) AND NOT EXISTS(SELECT 1 FROM aclexplode(coalesce(c.relacl,acldefault('r',c.relowner))) a WHERE a.grantee<>c.relowner) AND NOT EXISTS(SELECT 1 FROM (VALUES(0::oid),('anon'::regrole::oid),('authenticated'::regrole::oid),('service_role'::regrole::oid)) roles(id) CROSS JOIN unnest(ARRAY['SELECT','INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER']) priv(name) WHERE has_table_privilege(roles.id,c.oid,priv.name))))::text AS actual$read26$),
  (27,'collision','public.hotel_seven_arches_public_quote_issuances_absent','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read27$SELECT (to_regclass('public.hotel_seven_arches_public_quote_issuances') IS NULL)::text AS actual$read27$),
  (28,'collision','public.hotel_seven_arches_public_booking_transaction_context_absent','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read28$SELECT (to_regclass('public.hotel_seven_arches_public_booking_transaction_context') IS NULL)::text AS actual$read28$),
  (29,'collision','public.hotel_seven_arches_public_booking_receipts_absent','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read29$SELECT (to_regclass('public.hotel_seven_arches_public_booking_receipts') IS NULL)::text AS actual$read29$),
  (30,'collision','hotel_v2_seven_arches_public_quote_issuance_immutable_all_overloads_absent','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read30$SELECT (NOT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='hotel_v2_seven_arches_public_quote_issuance_immutable'))::text AS actual$read30$),
  (31,'collision','hotel_v2_seven_arches_public_booking_immutable_all_overloads_absent','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read31$SELECT (NOT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='hotel_v2_seven_arches_public_booking_immutable'))::text AS actual$read31$),
  (32,'collision','hotel_v2_seven_arches_public_booking_context_guard_all_overloads_absent','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read32$SELECT (NOT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='hotel_v2_seven_arches_public_booking_context_guard'))::text AS actual$read32$),
  (33,'collision','hotel_v2_seven_arches_public_booking_snapshot_guard_all_overloads_absent','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read33$SELECT (NOT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='hotel_v2_seven_arches_public_booking_snapshot_guard'))::text AS actual$read33$),
  (34,'collision','hotel_v2_seven_arches_public_booking_receipt_chain_is_exact_all_overloads_absent','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read34$SELECT (NOT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='hotel_v2_seven_arches_public_booking_receipt_chain_is_exact'))::text AS actual$read34$),
  (35,'collision','hotel_v2_seven_arches_public_quote_fingerprint_all_overloads_absent','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read35$SELECT (NOT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='hotel_v2_seven_arches_public_quote_fingerprint'))::text AS actual$read35$),
  (36,'collision','hotel_v2_public_quote_seven_arches_core_all_overloads_absent','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read36$SELECT (NOT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='hotel_v2_public_quote_seven_arches_core'))::text AS actual$read36$),
  (37,'collision','hotel_v2_public_quote_seven_arches_all_overloads_absent','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read37$SELECT (NOT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='hotel_v2_public_quote_seven_arches'))::text AS actual$read37$),
  (38,'collision','hotel_v2_public_create_seven_arches_booking_all_overloads_absent','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read38$SELECT (NOT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='hotel_v2_public_create_seven_arches_booking'))::text AS actual$read38$),
  (39,'collision','hotel_v2_partner_get_seven_arches_reviewed_pricing_all_overloads_absent','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read39$SELECT (NOT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='hotel_v2_partner_get_seven_arches_reviewed_pricing'))::text AS actual$read39$),
  (40,'collision','pricing_room_type_id_column_absent','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read40$SELECT (NOT EXISTS(SELECT 1 FROM pg_attribute WHERE attrelid=to_regclass('public.hotel_bookings') AND attname='pricing_room_type_id' AND NOT attisdropped))::text AS actual$read40$),
  (41,'collision','pricing_room_rate_id_column_absent','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read41$SELECT (NOT EXISTS(SELECT 1 FROM pg_attribute WHERE attrelid=to_regclass('public.hotel_bookings') AND attname='pricing_room_rate_id' AND NOT attisdropped))::text AS actual$read41$),
  (42,'collision','pricing_schedule_id_column_absent','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read42$SELECT (NOT EXISTS(SELECT 1 FROM pg_attribute WHERE attrelid=to_regclass('public.hotel_bookings') AND attname='pricing_schedule_id' AND NOT attisdropped))::text AS actual$read42$),
  (43,'collision','pricing_schedule_tier_id_column_absent','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read43$SELECT (NOT EXISTS(SELECT 1 FROM pg_attribute WHERE attrelid=to_regclass('public.hotel_bookings') AND attname='pricing_schedule_tier_id' AND NOT attisdropped))::text AS actual$read43$),
  (44,'collision','pricing_authority_token_column_absent','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read44$SELECT (NOT EXISTS(SELECT 1 FROM pg_attribute WHERE attrelid=to_regclass('public.hotel_bookings') AND attname='pricing_authority_token' AND NOT attisdropped))::text AS actual$read44$),
  (45,'collision','pricing_quote_fingerprint_column_absent','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read45$SELECT (NOT EXISTS(SELECT 1 FROM pg_attribute WHERE attrelid=to_regclass('public.hotel_bookings') AND attname='pricing_quote_fingerprint' AND NOT attisdropped))::text AS actual$read45$),
  (46,'collision','pricing_quote_expires_at_column_absent','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read46$SELECT (NOT EXISTS(SELECT 1 FROM pg_attribute WHERE attrelid=to_regclass('public.hotel_bookings') AND attname='pricing_quote_expires_at' AND NOT attisdropped))::text AS actual$read46$),
  (47,'collision','pricing_allocation_column_absent','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read47$SELECT (NOT EXISTS(SELECT 1 FROM pg_attribute WHERE attrelid=to_regclass('public.hotel_bookings') AND attname='pricing_allocation' AND NOT attisdropped))::text AS actual$read47$),
  (48,'collision','hotel_bookings_7a_authority_token_check_absent','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read48$SELECT (NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid=to_regclass('public.hotel_bookings') AND conname='hotel_bookings_7a_authority_token_check'))::text AS actual$read48$),
  (49,'collision','hotel_bookings_7a_quote_fingerprint_check_absent','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read49$SELECT (NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid=to_regclass('public.hotel_bookings') AND conname='hotel_bookings_7a_quote_fingerprint_check'))::text AS actual$read49$),
  (50,'collision','hotel_bookings_7a_allocation_check_absent','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read50$SELECT (NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid=to_regclass('public.hotel_bookings') AND conname='hotel_bookings_7a_allocation_check'))::text AS actual$read50$),
  (51,'collision','hotel_7a_public_quote_issuance_immutable_trigger_absent','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read51$SELECT (NOT EXISTS(SELECT 1 FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND t.tgname='hotel_7a_public_quote_issuance_immutable'))::text AS actual$read51$),
  (52,'collision','hotel_7a_public_booking_receipt_immutable_trigger_absent','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read52$SELECT (NOT EXISTS(SELECT 1 FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND t.tgname='hotel_7a_public_booking_receipt_immutable'))::text AS actual$read52$),
  (53,'collision','aa_hotel_7a_public_booking_rpc_guard_trigger_absent','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read53$SELECT (NOT EXISTS(SELECT 1 FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND t.tgname='aa_hotel_7a_public_booking_rpc_guard'))::text AS actual$read53$),
  (54,'collision','zz_hotel_7a_public_booking_snapshot_guard_trigger_absent','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read54$SELECT (NOT EXISTS(SELECT 1 FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND t.tgname='zz_hotel_7a_public_booking_snapshot_guard'))::text AS actual$read54$),
  (55,'lineage','pricing_activation_evolution_receipts_count','1',
    ARRAY['public.hotel_seven_arches_pricing_activation_evolution_receipts']::text[],ARRAY[]::text[],
    $read55$SELECT ((SELECT count(*) FROM public.hotel_seven_arches_pricing_activation_evolution_receipts))::text AS actual$read55$),
  (56,'lineage','pricing_activation_transaction_context_count','0',
    ARRAY['public.hotel_seven_arches_pricing_activation_transaction_context']::text[],ARRAY[]::text[],
    $read56$SELECT ((SELECT count(*) FROM public.hotel_seven_arches_pricing_activation_transaction_context))::text AS actual$read56$),
  (57,'lineage','independent_pricing_topology_receipts_count','2',
    ARRAY['public.hotel_seven_arches_independent_pricing_topology_receipts']::text[],ARRAY[]::text[],
    $read57$SELECT ((SELECT count(*) FROM public.hotel_seven_arches_independent_pricing_topology_receipts))::text AS actual$read57$),
  (58,'lineage','independent_pricing_evolution_receipts_count','1',
    ARRAY['public.hotel_seven_arches_independent_pricing_evolution_receipts']::text[],ARRAY[]::text[],
    $read58$SELECT ((SELECT count(*) FROM public.hotel_seven_arches_independent_pricing_evolution_receipts))::text AS actual$read58$),
  (59,'lineage','independent_pricing_authority_count','54',
    ARRAY['public.hotel_seven_arches_independent_pricing_authority']::text[],ARRAY[]::text[],
    $read59$SELECT ((SELECT count(*) FROM public.hotel_seven_arches_independent_pricing_authority))::text AS actual$read59$),
  (60,'pricing','upper_rate_exact','true',
    ARRAY['public.hotel_room_rates']::text[],ARRAY[]::text[],
    $read60$SELECT (EXISTS(SELECT 1 FROM public.hotel_room_rates WHERE id='7e420964-9cbf-4f1b-abd3-09840af5240f'::uuid AND hotel_id='9b6d99a0-923a-4fbc-be54-c066e856e6ca'::uuid AND room_type_id='b4ef504f-cdeb-4e3c-a54d-932146ef4e94'::uuid AND rate_plan_id='22e47a63-a630-4fb6-8f43-816f2d3fdc17'::uuid AND pricing_schedule_id='aec20731-7a56-35f0-334e-92b363351f02'::uuid AND base_nightly_rate=100 AND btrim(currency::text)='EUR' AND is_active AND review_status='reviewed'))::text AS actual$read60$),
  (61,'pricing','upper_schedule_exact','true',
    ARRAY['public.hotel_pricing_schedules']::text[],ARRAY[]::text[],
    $read61$SELECT (EXISTS(SELECT 1 FROM public.hotel_pricing_schedules WHERE id='aec20731-7a56-35f0-334e-92b363351f02'::uuid AND hotel_id='9b6d99a0-923a-4fbc-be54-c066e856e6ca'::uuid AND is_active AND review_status='reviewed' AND sharing_mode='independent'))::text AS actual$read61$),
  (62,'pricing','upper_active_tiers','27',
    ARRAY['public.hotel_pricing_schedule_occupancy_tiers']::text[],ARRAY[]::text[],
    $read62$SELECT ((SELECT count(*) FROM public.hotel_pricing_schedule_occupancy_tiers WHERE schedule_id='aec20731-7a56-35f0-334e-92b363351f02'::uuid AND is_active))::text AS actual$read62$),
  (63,'pricing','upper_authority_bindings','27',
    ARRAY['public.hotel_seven_arches_independent_pricing_authority','public.hotel_pricing_schedule_occupancy_tiers']::text[],ARRAY[]::text[],
    $read63$SELECT ((SELECT count(*) FROM public.hotel_seven_arches_independent_pricing_authority a JOIN public.hotel_pricing_schedule_occupancy_tiers t ON t.id=a.target_tier_id WHERE a.room_key='upper' AND a.hotel_id='9b6d99a0-923a-4fbc-be54-c066e856e6ca'::uuid AND a.room_type_id='b4ef504f-cdeb-4e3c-a54d-932146ef4e94'::uuid AND a.room_rate_id='7e420964-9cbf-4f1b-abd3-09840af5240f'::uuid AND a.independent_schedule_id='aec20731-7a56-35f0-334e-92b363351f02'::uuid AND t.schedule_id=a.independent_schedule_id AND t.is_active AND t.nightly_rate=a.current_nightly_rate AND t.version=a.current_target_version AND t.guest_count=a.guest_count AND t.threshold_nights=a.threshold_nights))::text AS actual$read63$),
  (64,'pricing','ground_rate_exact','true',
    ARRAY['public.hotel_room_rates']::text[],ARRAY[]::text[],
    $read64$SELECT (EXISTS(SELECT 1 FROM public.hotel_room_rates WHERE id='3320590d-632d-423f-80d0-fd021cba7293'::uuid AND hotel_id='9b6d99a0-923a-4fbc-be54-c066e856e6ca'::uuid AND room_type_id='825c01b7-9f82-492a-9c81-9b1d5cd7acd3'::uuid AND rate_plan_id='22e47a63-a630-4fb6-8f43-816f2d3fdc17'::uuid AND pricing_schedule_id='9d109336-64f3-3c57-4684-968b59c94c3b'::uuid AND base_nightly_rate=100 AND btrim(currency::text)='EUR' AND is_active AND review_status='reviewed'))::text AS actual$read64$),
  (65,'pricing','ground_schedule_exact','true',
    ARRAY['public.hotel_pricing_schedules']::text[],ARRAY[]::text[],
    $read65$SELECT (EXISTS(SELECT 1 FROM public.hotel_pricing_schedules WHERE id='9d109336-64f3-3c57-4684-968b59c94c3b'::uuid AND hotel_id='9b6d99a0-923a-4fbc-be54-c066e856e6ca'::uuid AND is_active AND review_status='reviewed' AND sharing_mode='independent'))::text AS actual$read65$),
  (66,'pricing','ground_active_tiers','27',
    ARRAY['public.hotel_pricing_schedule_occupancy_tiers']::text[],ARRAY[]::text[],
    $read66$SELECT ((SELECT count(*) FROM public.hotel_pricing_schedule_occupancy_tiers WHERE schedule_id='9d109336-64f3-3c57-4684-968b59c94c3b'::uuid AND is_active))::text AS actual$read66$),
  (67,'pricing','ground_authority_bindings','27',
    ARRAY['public.hotel_seven_arches_independent_pricing_authority','public.hotel_pricing_schedule_occupancy_tiers']::text[],ARRAY[]::text[],
    $read67$SELECT ((SELECT count(*) FROM public.hotel_seven_arches_independent_pricing_authority a JOIN public.hotel_pricing_schedule_occupancy_tiers t ON t.id=a.target_tier_id WHERE a.room_key='ground' AND a.hotel_id='9b6d99a0-923a-4fbc-be54-c066e856e6ca'::uuid AND a.room_type_id='825c01b7-9f82-492a-9c81-9b1d5cd7acd3'::uuid AND a.room_rate_id='3320590d-632d-423f-80d0-fd021cba7293'::uuid AND a.independent_schedule_id='9d109336-64f3-3c57-4684-968b59c94c3b'::uuid AND t.schedule_id=a.independent_schedule_id AND t.is_active AND t.nightly_rate=a.current_nightly_rate AND t.version=a.current_target_version AND t.guest_count=a.guest_count AND t.threshold_nights=a.threshold_nights))::text AS actual$read67$),
  (68,'safe_predicate','hotel_v2_seven_arches_independent_pricing_topology_is_exact','true',
    ARRAY[]::text[],ARRAY['public.hotel_v2_seven_arches_independent_pricing_topology_is_exact()']::text[],
    $read68$SELECT (public.hotel_v2_seven_arches_independent_pricing_topology_is_exact())::text AS actual$read68$),
  (69,'safe_predicate','hotel_v2_seven_arches_reviewed_pricing_receipt_chain_is_exact','true',
    ARRAY[]::text[],ARRAY['public.hotel_v2_seven_arches_reviewed_pricing_receipt_chain_is_exact()']::text[],
    $read69$SELECT (public.hotel_v2_seven_arches_reviewed_pricing_receipt_chain_is_exact())::text AS actual$read69$),
  (70,'safe_predicate','hotel_v2_admin_c_seven_kamares_allocation_contract_is_exact','true',
    ARRAY[]::text[],ARRAY['public.hotel_v2_admin_c_seven_kamares_allocation_contract_is_exact()']::text[],
    $read70$SELECT (public.hotel_v2_admin_c_seven_kamares_allocation_contract_is_exact())::text AS actual$read70$),
  (71,'safe_predicate','hotel_v2_seven_arches_payment_policy_lineage_is_exact','true',
    ARRAY[]::text[],ARRAY['public.hotel_v2_seven_arches_payment_policy_lineage_is_exact()']::text[],
    $read71$SELECT (public.hotel_v2_seven_arches_payment_policy_lineage_is_exact())::text AS actual$read71$),
  (72,'safe_predicate','hotel_v2_seven_arches_pricing_activation_current_is_safe','true',
    ARRAY[]::text[],ARRAY['public.hotel_v2_seven_arches_pricing_activation_current_is_safe()']::text[],
    $read72$SELECT (public.hotel_v2_seven_arches_pricing_activation_current_is_safe())::text AS actual$read72$),
  (73,'safe_predicate','hotel_v2_7a_pricing_activation_transaction_is_preserved','true',
    ARRAY[]::text[],ARRAY['public.hotel_v2_7a_pricing_activation_transaction_is_preserved()']::text[],
    $read73$SELECT (public.hotel_v2_7a_pricing_activation_transaction_is_preserved())::text AS actual$read73$),
  (74,'parity','core_case_count','100',
    ARRAY[]::text[],ARRAY['public.hotel_v2_seven_arches_reviewed_pricing_oracle()']::text[],
    $read74$SELECT (public.hotel_v2_seven_arches_reviewed_pricing_oracle()->>'core_case_count')::text AS actual$read74$),
  (75,'parity','core_mismatch_count','0',
    ARRAY[]::text[],ARRAY['public.hotel_v2_seven_arches_reviewed_pricing_oracle()']::text[],
    $read75$SELECT (public.hotel_v2_seven_arches_reviewed_pricing_oracle()->>'core_mismatch_count')::text AS actual$read75$),
  (76,'parity','guest_one_case_count','20',
    ARRAY[]::text[],ARRAY['public.hotel_v2_seven_arches_reviewed_pricing_oracle()']::text[],
    $read76$SELECT (public.hotel_v2_seven_arches_reviewed_pricing_oracle()->>'guest_one_case_count')::text AS actual$read76$),
  (77,'parity','guest_one_mismatch_count','0',
    ARRAY[]::text[],ARRAY['public.hotel_v2_seven_arches_reviewed_pricing_oracle()']::text[],
    $read77$SELECT (public.hotel_v2_seven_arches_reviewed_pricing_oracle()->>'guest_one_mismatch_count')::text AS actual$read77$),
  (78,'lineage','scoped_lineage_present','true',
    ARRAY[]::text[],ARRAY['public.hotel_v2_seven_arches_pricing_scoped_lineage()']::text[],
    $read78$SELECT (public.hotel_v2_seven_arches_pricing_scoped_lineage() IS NOT NULL)::text AS actual$read78$),
  (79,'commercial','active_reviewed_commission_count','1',
    ARRAY['public.hotel_commission_policies']::text[],ARRAY[]::text[],
    $read79$SELECT ((SELECT count(*) FROM public.hotel_commission_policies WHERE hotel_id='9b6d99a0-923a-4fbc-be54-c066e856e6ca'::uuid AND is_active AND review_status='reviewed'))::text AS actual$read79$),
  (80,'commercial','commission_EUR10_exact','1',
    ARRAY['public.hotel_commission_policies']::text[],ARRAY[]::text[],
    $read80$SELECT ((SELECT count(*) FROM public.hotel_commission_policies WHERE hotel_id='9b6d99a0-923a-4fbc-be54-c066e856e6ca'::uuid AND is_active AND review_status='reviewed' AND commission_mode='per_allocated_room_per_night' AND amount=10 AND btrim(currency::text)='EUR'))::text AS actual$read80$),
  (81,'flags','legacy_architecture','true',
    ARRAY['public.hotels']::text[],ARRAY[]::text[],
    $read81$SELECT (EXISTS(SELECT 1 FROM public.hotels WHERE id='9b6d99a0-923a-4fbc-be54-c066e856e6ca'::uuid AND architecture_version='legacy'))::text AS actual$read81$),
  (82,'flags','hotel_rooms_v2_enabled','false',
    ARRAY['public.site_settings']::text[],ARRAY[]::text[],
    $read82$SELECT ((SELECT hotel_rooms_v2_enabled FROM public.site_settings WHERE id=1))::text AS actual$read82$),
  (83,'flags','hotel_external_sync_enabled','true',
    ARRAY['public.site_settings']::text[],ARRAY[]::text[],
    $read83$SELECT ((SELECT hotel_external_sync_enabled FROM public.site_settings WHERE id=1))::text AS actual$read83$),
  (84,'flags','hotel_instant_booking_enabled','false',
    ARRAY['public.site_settings']::text[],ARRAY[]::text[],
    $read84$SELECT ((SELECT hotel_instant_booking_enabled FROM public.site_settings WHERE id=1))::text AS actual$read84$),
  (85,'flags','hotel_stripe_connect_enabled','false',
    ARRAY['public.site_settings']::text[],ARRAY[]::text[],
    $read85$SELECT ((SELECT hotel_stripe_connect_enabled FROM public.site_settings WHERE id=1))::text AS actual$read85$),
  (86,'maintenance','unconsumed_live_activation_reviews','0',
    ARRAY['public.hotel_seven_arches_pricing_activation_reviews']::text[],ARRAY[]::text[],
    $read86$SELECT ((SELECT count(*) FROM public.hotel_seven_arches_pricing_activation_reviews WHERE consumed_at IS NULL AND expires_at>statement_timestamp()))::text AS actual$read86$),
  (87,'maintenance','pending_property_proposals','0',
    ARRAY['public.hotel_partner_property_drafts']::text[],ARRAY[]::text[],
    $read87$SELECT ((SELECT count(*) FROM public.hotel_partner_property_drafts WHERE hotel_id='9b6d99a0-923a-4fbc-be54-c066e856e6ca'::uuid AND status='pending_admin_review'))::text AS actual$read87$),
  (88,'maintenance','open_jobs','0',
    ARRAY['hotels_v2_private.hotel_external_calendar_sync_jobs']::text[],ARRAY[]::text[],
    $read88$SELECT ((SELECT count(*) FROM hotels_v2_private.hotel_external_calendar_sync_jobs WHERE hotel_id='9b6d99a0-923a-4fbc-be54-c066e856e6ca'::uuid AND status IN('queued','leased','running')))::text AS actual$read88$),
  (89,'maintenance','active_leases','0',
    ARRAY['hotels_v2_private.hotel_external_calendar_sync_jobs']::text[],ARRAY[]::text[],
    $read89$SELECT ((SELECT count(*) FROM hotels_v2_private.hotel_external_calendar_sync_jobs WHERE hotel_id='9b6d99a0-923a-4fbc-be54-c066e856e6ca'::uuid AND status IN('leased','running') AND leased_until>statement_timestamp()))::text AS actual$read89$),
  (90,'maintenance','stale_leases','0',
    ARRAY['hotels_v2_private.hotel_external_calendar_sync_jobs']::text[],ARRAY[]::text[],
    $read90$SELECT ((SELECT count(*) FROM hotels_v2_private.hotel_external_calendar_sync_jobs WHERE hotel_id='9b6d99a0-923a-4fbc-be54-c066e856e6ca'::uuid AND status IN('leased','running') AND (leased_until IS NULL OR leased_until<=statement_timestamp())))::text AS actual$read90$),
  (91,'maintenance','other_booking_relation_locks','0',
    ARRAY[]::text[],ARRAY[]::text[],
    $read91$SELECT ((SELECT count(*) FROM pg_locks WHERE relation=to_regclass('public.hotel_bookings') AND pid IS DISTINCT FROM pg_backend_pid()))::text AS actual$read91$),
  (92,'maintenance','protected_waits_or_write_locks','0',
    ARRAY[]::text[],ARRAY[]::text[],
    $read92$SELECT ((SELECT count(*) FROM pg_locks l JOIN pg_class c ON c.oid=l.relation JOIN pg_namespace n ON n.oid=c.relnamespace WHERE l.pid IS DISTINCT FROM pg_backend_pid() AND n.nspname IN('public','hotels_v2_private') AND (c.relname='hotels' OR left(c.relname,6)='hotel_') AND (NOT l.granted OR l.mode IN('RowExclusiveLock','ShareUpdateExclusiveLock','ShareLock','ShareRowExclusiveLock','ExclusiveLock','AccessExclusiveLock'))))::text AS actual$read92$),
  (93,'maintenance','client_transactions_over_five_minutes','0',
    ARRAY[]::text[],ARRAY[]::text[],
    $read93$SELECT ((SELECT count(*) FROM pg_stat_activity WHERE pid IS DISTINCT FROM pg_backend_pid() AND backend_type='client backend' AND xact_start<statement_timestamp()-interval '5 minutes'))::text AS actual$read93$),
  (94,'maintenance','inventory_visibility','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read94$SELECT ((SELECT rolsuper OR pg_has_role(current_user,'pg_read_all_stats','MEMBER') FROM pg_roles WHERE rolname=current_user))::text AS actual$read94$),
  (95,'future','114425_helper_absent','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read95$SELECT (to_regprocedure('public.hotel_v2_external_calendar_site_settings_fingerprint()') IS NULL)::text AS actual$read95$),
  (96,'future','114450_receipt_absent','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read96$SELECT (to_regclass('hotels_v2_private.hotel_external_calendar_provider_evolution_receipts') IS NULL)::text AS actual$read96$),
  (97,'future','114450_bridge_absent','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read97$SELECT (to_regprocedure('public.hotel_v2_external_calendar_provider_lineage_bridge_is_exact()') IS NULL)::text AS actual$read97$),
  (98,'dependency','booking_relation_exists','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read98$SELECT (to_regclass('public.hotel_bookings') IS NOT NULL)::text AS actual$read98$),
  (99,'dependency','coupon_signature_exists','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read99$SELECT (to_regprocedure('public.service_coupon_quote(text,text,numeric,timestamptz,uuid,text[],uuid,text)') IS NOT NULL)::text AS actual$read99$),
  (100,'collision','public_bridge_relation_index_names_absent','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read100$SELECT (NOT EXISTS(SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND starts_with(c.relname,'hotel_seven_arches_public_')))::text AS actual$read100$),
  (101,'collision','public_bridge_row_type_names_absent','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read101$SELECT (NOT EXISTS(SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid=t.typnamespace WHERE n.nspname='public' AND (starts_with(t.typname,'hotel_seven_arches_public_') OR starts_with(t.typname,'_hotel_seven_arches_public_'))))::text AS actual$read101$),
  (102,'workspace_contract','canonical_workspace_security_exact','true',
    ARRAY[]::text[],ARRAY[]::text[],
    $read102$SELECT (EXISTS(SELECT 1 FROM pg_proc p JOIN pg_language l ON l.oid=p.prolang WHERE p.oid=to_regprocedure('public.hotel_v2_partner_get_workspace(uuid,uuid,date,date)') AND p.proowner='postgres'::regrole AND p.prosecdef AND p.provolatile='s' AND l.lanname='plpgsql' AND p.proconfig=ARRAY['search_path=pg_catalog, public, auth']::text[] AND has_function_privilege('postgres',p.oid,'EXECUTE') AND has_function_privilege('authenticated',p.oid,'EXECUTE') AND NOT has_function_privilege(0::oid,p.oid,'EXECUTE') AND NOT has_function_privilege('anon',p.oid,'EXECUTE') AND NOT has_function_privilege('service_role',p.oid,'EXECUTE')))::text AS actual$read102$),
  (103,'history','recorded_114460','0',
    ARRAY['supabase_migrations.schema_migrations']::text[],ARRAY[]::text[],
    $read103$SELECT count(*)::text AS actual FROM supabase_migrations.schema_migrations WHERE version::text='20260811446000'$read103$),
  (104,'history','recorded_114470','0',
    ARRAY['supabase_migrations.schema_migrations']::text[],ARRAY[]::text[],
    $read104$SELECT count(*)::text AS actual FROM supabase_migrations.schema_migrations WHERE version::text='20260811447000'$read104$),
  (105,'history','recorded_114480','0',
    ARRAY['supabase_migrations.schema_migrations']::text[],ARRAY[]::text[],
    $read105$SELECT count(*)::text AS actual FROM supabase_migrations.schema_migrations WHERE version::text='20260811448000'$read105$),
  (106,'maintenance','booking_waiting_writer_count','0',
    ARRAY['public.hotel_bookings']::text[],ARRAY[]::text[],
    $read106$SELECT count(*)::text AS actual FROM pg_locks WHERE relation=to_regclass('public.hotel_bookings') AND pid IS DISTINCT FROM pg_backend_pid() AND NOT granted AND mode IN('RowExclusiveLock','ShareUpdateExclusiveLock','ShareLock','ShareRowExclusiveLock','ExclusiveLock','AccessExclusiveLock')$read106$),
  (107,'dependency','booking_relation_identity_exact','true',
    ARRAY['public.hotel_bookings']::text[],ARRAY[]::text[],
    $read107$SELECT EXISTS(SELECT 1 FROM pg_class WHERE oid=to_regclass('public.hotel_bookings') AND relkind='r' AND relpersistence='p' AND relowner='postgres'::regrole)::text AS actual$read107$),
  (108,'flags','public_booking_disabled','true',
    ARRAY['public.hotels','public.site_settings']::text[],ARRAY[]::text[],
    $read108$SELECT (EXISTS(SELECT 1 FROM public.hotels WHERE id='9b6d99a0-923a-4fbc-be54-c066e856e6ca'::uuid AND architecture_version='legacy') AND EXISTS(SELECT 1 FROM public.site_settings WHERE id=1 AND hotel_rooms_v2_enabled IS FALSE AND hotel_instant_booking_enabled IS FALSE))::text AS actual$read108$),
  (109,'maintenance','all_booking_related_relation_locks','0',
    ARRAY['public.hotel_bookings']::text[],ARRAY[]::text[],
    $read109$SELECT count(*)::text AS actual FROM pg_locks l WHERE l.pid IS DISTINCT FROM pg_backend_pid() AND l.relation IN (SELECT oid FROM pg_class WHERE oid=to_regclass('public.hotel_bookings') UNION SELECT indexrelid FROM pg_index WHERE indrelid=to_regclass('public.hotel_bookings') UNION SELECT reltoastrelid FROM pg_class WHERE oid=to_regclass('public.hotel_bookings') AND reltoastrelid<>0)$read109$),
  (110,'reconciliation','recorded_114416','1',
    ARRAY['supabase_migrations.schema_migrations']::text[],ARRAY[]::text[],
    $read110$SELECT count(*)::text AS actual FROM supabase_migrations.schema_migrations WHERE version::text='20260811441600'$read110$),
  (111,'reconciliation','reconciliation_anchor_exact','true',
    ARRAY['hotels_lineage_private.reconciliation_receipts']::text[],ARRAY['hotels_lineage_private.current_anchor_is_exact()']::text[],
    $read111$SELECT hotels_lineage_private.current_anchor_is_exact()::text AS actual$read111$),
  (112,'reconciliation','successor_certificates_absent','0',
    ARRAY['hotels_lineage_private.successor_receipts']::text[],ARRAY[]::text[],
    $read112$SELECT count(*)::text AS actual FROM hotels_lineage_private.successor_receipts$read112$)
),
eligibility AS MATERIALIZED (
  SELECT s.*,
    NOT EXISTS(SELECT 1 FROM unnest(s.required_relations) r(name)
      WHERE to_regclass(r.name) IS NULL)
    AND NOT EXISTS(SELECT 1 FROM unnest(s.required_functions) f(signature)
      LEFT JOIN pg_proc p ON p.oid=to_regprocedure(f.signature)
      WHERE p.oid IS NULL OR p.provolatile NOT IN('s','i')
        OR p.proowner<>'postgres'::regrole)
    AND (cardinality(s.required_functions)=0
      OR NOT EXISTS(SELECT 1 FROM pin_results WHERE exact IS NOT TRUE))
      AS eligible
  FROM specs s
),
measurements AS MATERIALIZED (
  SELECT e.*,
    CASE WHEN eligible THEN
      (xpath('/table/row/actual/text()',
        query_to_xml(e.read_query,true,false,'')))[1]::text
    ELSE NULL END AS actual
  FROM eligibility e
),
leaves AS MATERIALIZED (
  SELECT ordinal,section,leaf_name,expected,actual,
    eligible AND actual IS NOT NULL AND actual=expected AS pass,
    CASE WHEN NOT eligible THEN 'REQUIRED_OBJECT_OR_SOURCE_CONTRACT_UNAVAILABLE'
      WHEN actual IS NULL THEN 'NULL_RESULT_FAIL_CLOSED'
      ELSE 'SAFE_SCALAR_ONLY' END AS safe_context
  FROM measurements
  UNION ALL
  SELECT 112+row_number() OVER(ORDER BY signature)::integer,
    'source_security',signature,'true',exact::text,exact IS TRUE,safe_context
  FROM pin_results
),
totals AS (
  SELECT bool_and(pass IS TRUE) AS ready,
    coalesce(jsonb_agg(leaf_name ORDER BY ordinal)
      FILTER(WHERE pass IS NOT TRUE),'[]'::jsonb) AS blockers,
    count(*) AS required_count,count(*) FILTER(WHERE pass IS TRUE) AS passed_count
  FROM leaves
)
SELECT section,ordinal,leaf_name,expected,actual,pass,safe_context,
  NULL::boolean AS "FINAL_PREACTION_READY",NULL::jsonb AS blocker_codes,
  NULL::bigint AS required_leaf_count,NULL::bigint AS passed_leaf_count
FROM leaves
UNION ALL
SELECT 'final_gate',127,'FINAL_PREACTION_READY','true',
  ready::text,ready,
  'RECOVERY_POINT_EXTERNAL_GATE=HUMAN_CONFIRMED; RECOVERY_POINT=2026-09-08 05:38:06 UTC; SQL_BACKUP_PROOF=NO; NOT_WRITE_AUTHORIZATION',
  ready,blockers,required_count,passed_count
FROM totals
ORDER BY ordinal;
ROLLBACK;
